(asdf:load-system "reed")
(in-package :reed)
;; Verify each spectral codebook + scalefactor codebook: feed codeword bits, expect index.
(defun bits->octets (bitlist)
  (let* ((n (length bitlist)) (nb (ceiling n 8))
         (v (make-array nb :element-type '(unsigned-byte 8) :initial-element 0)))
    (loop for b in bitlist for i from 0
          do (when (= b 1) (setf (aref v (floor i 8)) (logior (aref v (floor i 8)) (ash 1 (- 7 (mod i 8)))))))
    v))
(defun code->bits (code len) (loop for i from (1- len) downto 0 collect (logand (ash code (- i)) 1)))
(let ((bad 0) (tot 0))
  (dotimes (cb 11)
    (let ((codes (aref +aac-spec-codes+ cb)) (bits (aref +aac-spec-bits+ cb))
          (dec (aac-spec-decoder cb)))
      (dotimes (i (length codes))
        (incf tot)
        (let* ((bl (code->bits (aref codes i) (aref bits i)))
               (br (make-bitreader (bits->octets bl)))
               (sym (aac-huff-decode br dec)))
          (unless (and (= sym i) (= (br-pos br) (aref bits i)))
            (incf bad) (when (< bad 6) (format t "cb~a sym~a got ~a pos ~a/~a~%" (1+ cb) i sym (br-pos br) (aref bits i))))))))
  ;; scalefactor cb
  (let ((dec (aac-sf-decoder)))
    (dotimes (i 121)
      (incf tot)
      (let* ((bl (code->bits (aref +aac-sf-codes+ i) (aref +aac-sf-bits+ i)))
             (br (make-bitreader (bits->octets bl)))
             (sym (aac-huff-decode br dec)))
        (unless (and (= sym i) (= (br-pos br) (aref +aac-sf-bits+ i))) (incf bad)))))
  (format t "~&HUFF-CHECK bad=~a / tot=~a~%" bad tot))
