import re, sys
def carray(text, name):
    """The initialiser braces of a C array declaration, as a flat list of ints.

    SIGNEDNESS COMES FROM THE DECLARED C TYPE and has to: ff_ac3_floor_tab is int16_t and its last
    entry is written 0xf800, which is -2048.  Read unsigned it is 63488, the masking floor goes to
    the moon, every bit allocation pointer comes out zero, and the decoder reads no mantissas at
    all -- a failure that looks nothing like a table transcribed wrong."""
    i = text.index(name)
    decl = text[max(0, i-40):i]
    signed = ('int8_t' in decl or 'int16_t' in decl or 'int32_t' in decl) and 'uint' not in decl
    width = 8 if 'int8_t' in decl else (16 if 'int16_t' in decl else 32)
    j = text.index('{', i)
    depth = 0
    for k in range(j, len(text)):
        if text[k] == '{': depth += 1
        elif text[k] == '}':
            depth -= 1
            if depth == 0: end = k; break
    body = text[j:end+1]
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    body = re.sub(r'//[^\n]*', '', body)
    vals = [int(t, 0) for t in re.findall(r'-?\b(?:0[xX][0-9a-fA-F]+|\d+)\b', body)]
    if signed:
        lim = 1 << (width - 1)
        vals = [v - 2 * lim if v >= lim else v for v in vals]
    return vals

tab = open('ac3tab.c').read()
ac3 = open('ac3.c').read()
dec = open('ac3dec_data.c').read()

T = {}
T['frame-size']        = (carray(tab, 'ff_ac3_frame_size_tab[38][3]'), 38*3)
T['channels']          = (carray(tab, 'ff_ac3_channels_tab[8]'), 8)
T['sample-rate']       = (carray(tab, 'ff_ac3_sample_rate_tab[]'), 4)
T['bitrate']           = (carray(tab, 'ff_ac3_bitrate_tab[19]'), 19)
T['rematrix-band']     = (carray(tab, 'ff_ac3_rematrix_band_tab[5]'), 5)
T['bap']               = (carray(tab, 'ff_ac3_bap_tab[64]'), 64)
T['slow-decay']        = (carray(tab, 'ff_ac3_slow_decay_tab[4]'), 4)
T['fast-decay']        = (carray(tab, 'ff_ac3_fast_decay_tab[4]'), 4)
T['slow-gain']         = (carray(tab, 'ff_ac3_slow_gain_tab[4]'), 4)
T['db-per-bit']        = (carray(tab, 'ff_ac3_db_per_bit_tab[4]'), 4)
T['floor']             = (carray(tab, 'ff_ac3_floor_tab[8]'), 8)
T['fast-gain']         = (carray(tab, 'ff_ac3_fast_gain_tab[8]'), 8)
T['band-start']        = (carray(ac3, 'ff_ac3_band_start_tab[AC3_CRITICAL_BANDS+1]'), 51)
T['bin-to-band']       = (carray(ac3, 'ff_ac3_bin_to_band_tab[253]'), 253)
T['log-add']           = (carray(ac3, 'ac3_log_add_tab[260]'), 260)
T['hearing-threshold'] = (carray(ac3, 'ac3_hearing_threshold_tab[AC3_CRITICAL_BANDS][3]'), 50*3)
T['quantization']      = (carray(dec, 'ff_ac3_quantization_tab[16]'), 16)

bad = 0
for k,(v,n) in T.items():
    if len(v) != n:
        print(f"  LENGTH {k}: got {len(v)} want {n}", file=sys.stderr); bad += 1
if bad: sys.exit(1)

# ---- invariants, so a mis-parse is caught here and not in the audio -------------------------
bs = T['band-start'][0]
assert bs[0] == 0 and bs[-1] == 253, bs[:3]
assert all(bs[i] < bs[i+1] for i in range(50)), "band starts must ascend"
b2b = T['bin-to-band'][0]
assert all(b2b[i] <= b2b[i+1] for i in range(252)), "bin->band must not go backwards"
assert max(b2b) == 49 and b2b[0] == 0
for bin_, band in enumerate(b2b):
    assert bs[band] <= bin_ < bs[band+1], f"bin {bin_} maps to band {band} outside its range"
bap = T['bap'][0]
assert min(bap) == 0 and max(bap) == 15, "bap values are 0..15"
assert all(bap[i] <= bap[i+1] for i in range(63)), "bap must not decrease with signal-to-mask"
assert T['sample-rate'][0] == [48000, 44100, 32000, 0]
la = T['log-add'][0]
assert la[0] == 64 and all(la[i] >= la[i+1] for i in range(259)), "log-add must decay"
fs = T['frame-size'][0]
assert fs[0:3] == [64, 69, 96], fs[0:3]
fl = T['floor'][0]
assert all(fl[i] > fl[i+1] for i in range(7)), "the masking floor must decrease"
assert fl[0] == 0x2f0 and fl[7] == -2048, fl
q = T['quantization'][0]
assert q == [0,3,5,7,11,15,5,6,7,8,9,10,11,12,14,16]

def lisp(name, vals, dims=None):
    if dims is None:
        return (f"(defparameter +ac3-{name}+\n  (make-array {len(vals)} :element-type 'fixnum\n"
                f"    :initial-contents '({' '.join(map(str,vals))})))\n"
                f"(declaim (type (simple-array fixnum ({len(vals)})) +ac3-{name}+))\n")
    r, c = dims
    rows = [vals[i*c:(i+1)*c] for i in range(r)]
    body = ' '.join('(' + ' '.join(map(str,row)) + ')' for row in rows)
    return (f"(defparameter +ac3-{name}+\n  (make-array '({r} {c}) :element-type 'fixnum\n"
            f"    :initial-contents '({body})))\n"
            f"(declaim (type (simple-array fixnum ({r} {c})) +ac3-{name}+))\n")

hdr = '''\
;;;; src/ac3/tables.lisp — GENERATED by test/gen-ac3-tables.py.  Do not edit.
;;;;
;;;; Every constant AC-3 needs that is not derivable, transcribed mechanically from ffmpeg's
;;;; ac3tab.c, ac3.c and ac3dec_data.c by parsing the C rather than by retyping it.  The generator
;;;; asserts what each table has to be true of before emitting anything: band starts ascend and
;;;; span 0..253, every bin maps into its own band's range, the bit-allocation pointers are
;;;; monotonic in signal-to-mask ratio and lie in 0..15, and the log-add curve decays.  A table that
;;;; parsed wrong fails there rather than three layers down in the audio.
;;;;
;;;; The mantissa dequantisation tables are NOT here: they are a formula, (2m - (L-1))/L for an
;;;; L-level symmetric quantiser, and computing them says what they are.

(in-package #:reed)

'''
out = [hdr]
out.append(lisp('frame-size', T['frame-size'][0], (38,3)))
for k in ['channels','sample-rate','bitrate','rematrix-band','bap','slow-decay','fast-decay',
          'slow-gain','db-per-bit','floor','fast-gain','band-start','bin-to-band','log-add',
          'quantization']:
    out.append(lisp(k, T[k][0]))
out.append(lisp('hearing-threshold', T['hearing-threshold'][0], (50,3)))
open('/home/claude/reed/src/ac3/tables.lisp','w').write('\n'.join(out))
print("wrote", sum(len(v) for v,_ in T.values()), "constants across", len(T), "tables; all invariants hold")
