#!/usr/bin/env python3
"""Extract AAC-LC constant tables from ffmpeg's aactab.c into a Lisp file.

Only the *table data* (codeword lengths/codewords, scalefactor-window-band
offsets, TNS coefficient de-quantization maps, sample rates) is taken; these
are numeric facts from ISO/IEC 14496-3 (reproduced by ffmpeg).  The decoder
algorithms themselves are written from the ISO specification.
"""
import os, re, sys

# Source aactab.c (from an ffmpeg checkout) and the Lisp output file; both are
# overridable via the environment. OUT defaults to <repo>/src/aac/tables.lisp.
_HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.environ.get("AACTAB_C", "/tmp/aactab.c")
OUT = os.environ.get("REED_AAC_TABLES",
                     os.path.join(_HERE, os.pardir, "src", "aac", "tables.lisp"))

txt = open(SRC).read()

def arr(name):
    m = re.search(r'\b'+re.escape(name)+r'\s*\[[^\]]*\]\s*=\s*\{(.*?)\}\s*;', txt, re.S)
    if not m:
        raise SystemExit("missing "+name)
    body = m.group(1)
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    nums = re.findall(r'-?0x[0-9a-fA-F]+|-?\d+\.\d+|-?\d+', body)
    out = []
    for n in nums:
        if n.lower().startswith('0x') or n.lower().startswith('-0x'):
            out.append(int(n, 16))
        elif '.' in n:
            out.append(float(n))
        else:
            out.append(int(n))
    return out

def lisp_ints(xs):
    return ' '.join(str(x) for x in xs)

def lisp_floats(xs):
    return ' '.join(('%.8fd0' % x) for x in xs)

lines = []
w = lines.append
w(""";;;; src/aac/tables.lisp --- AAC-LC constant tables.
;;;;
;;;; GENERATED by test/gen-aac-tables.py from the numeric tables of ISO/IEC
;;;; 14496-3 (Huffman codebooks, scalefactor-window-band offsets, TNS coef
;;;; maps).  Do not edit by hand; edit the generator.  These are spec facts.
(in-package #:reed)
""")

# ---- sample rates ---------------------------------------------------------
rates = [96000,88200,64000,48000,44100,32000,24000,22050,16000,12000,11025,8000,7350,0,0,0]
w(";;; ISO 14496-3 Table 1.16 sampling-frequency index -> Hz")
w("(defparameter +aac-sample-rates+")
w("  (make-array 16 :element-type 'fixnum :initial-contents (list %s)))\n" % lisp_ints(rates))

# ---- spectral Huffman codebooks 1..11 ------------------------------------
codes = [arr("codes%d"%i) for i in range(1,12)]
bits  = [arr("bits%d"%i)  for i in range(1,12)]
sizes = [81,81,81,81,81,81,64,64,169,169,289]
for i in range(11):
    assert len(codes[i])==sizes[i] and len(bits[i])==sizes[i], (i,len(codes[i]),len(bits[i]))

def emit_vecvec(name, vs, hexp=False):
    w("(defparameter %s" % name)
    w("  (vector")
    for v in vs:
        if hexp:
            w("   #(%s)" % ' '.join('#x%x'%x for x in v))
        else:
            w("   #(%s)" % lisp_ints(v))
    w("  ))\n")

w(";;; Spectral codebooks 1..11: codeword bit patterns and their bit lengths,")
w(";;; indexed by symbol index (ISO 14496-3 Tables 4.A.2..4.A.12 / clause 4.6.3).")
emit_vecvec("+aac-spec-codes+", codes, hexp=True)
emit_vecvec("+aac-spec-bits+",  bits)

# per-codebook params: dim, unsigned-p, mod, off, esc-p
# cb:      1     2     3     4     5     6     7     8     9    10    11
params = [
 (4,0,3,1,0),(4,0,3,1,0),(4,1,3,0,0),(4,1,3,0,0),
 (2,0,9,4,0),(2,0,9,4,0),(2,1,8,0,0),(2,1,8,0,0),
 (2,1,13,0,0),(2,1,13,0,0),(2,1,17,0,1)]
w(";;; Per-codebook: (dimension unsigned-p modulo offset escape-p)")
w("(defparameter +aac-cb-params+")
w("  (vector")
for p in params:
    w("   #(%d %d %d %d %d)" % p)
w("  ))\n")

# ---- scalefactor codebook ------------------------------------------------
sfc = arr("ff_aac_scalefactor_code"); sfb = arr("ff_aac_scalefactor_bits")
assert len(sfc)==121 and len(sfb)==121
w(";;; Differential scalefactor Huffman codebook (121 entries, symbol-60 = delta)")
w("(defparameter +aac-sf-codes+ #(%s))" % ' '.join('#x%x'%x for x in sfc))
w("(defparameter +aac-sf-bits+  #(%s))\n" % lisp_ints(sfb))

# ---- scalefactor-window-band offsets -------------------------------------
swb1024 = {r:arr("swb_offset_1024_%d"%r) for r in (96,64,48,32,24,16,8)}
swb128  = {r:arr("swb_offset_128_%d"%r)  for r in (96,48,24,16,8)}
# sf-index -> which offset table (ISO / faad2 grouping)
map1024 = [96,96,64,48,48,32,24,24,16,16,16,8,8]
map128  = [96,96,96,48,48,48,24,24,16,16,16,8,8]
def emit_swb(name, mapping, tables):
    w("(defparameter %s" % name)
    w("  (vector")
    for r in mapping:
        w("   #(%s)" % lisp_ints(tables[r]))
    w("  ))\n")
w(";;; Scalefactor window band offsets per sampling-frequency index (0..12).")
w(";;; Last entry of each vector is the transform length (1024 / 128).")
emit_swb("+aac-swb-1024+", map1024, swb1024)
emit_swb("+aac-swb-128+",  map128,  swb128)

# ---- TNS max bands -------------------------------------------------------
tmb1024 = arr("ff_tns_max_bands_1024"); tmb128 = arr("ff_tns_max_bands_128")
w("(defparameter +aac-tns-max-bands-1024+ #(%s))" % lisp_ints(tmb1024))
w("(defparameter +aac-tns-max-bands-128+  #(%s))\n" % lisp_ints(tmb128))

# ---- TNS coef -> parcor maps (indexed 2*coef_compress + coef_res) --------
m03 = arr("tns_tmp2_map_0_3"); m04 = arr("tns_tmp2_map_0_4")
m13 = arr("tns_tmp2_map_1_3"); m14 = arr("tns_tmp2_map_1_4")
w(";;; TNS quantized-coef -> reflection(parcor) coefficient; index 2*compress+res")
w("(defparameter +aac-tns-tmp2-map+")
w("  (vector")
for m in (m03,m04,m13,m14):
    w("   (make-array %d :element-type 'double-float :initial-contents '(%s))" % (len(m), lisp_floats(m)))
w("  ))\n")

open(OUT,"w").write("\n".join(lines))
print("wrote", OUT, "lines", len(lines))
