;;;; src/aac/tables.lisp --- AAC-LC constant tables.
;;;;
;;;; GENERATED by test/gen-aac-tables.py from the numeric tables of ISO/IEC
;;;; 14496-3 (Huffman codebooks, scalefactor-window-band offsets, TNS coef
;;;; maps).  Do not edit by hand; edit the generator.  These are spec facts.
(in-package #:reed)

;;; ISO 14496-3 Table 1.16 sampling-frequency index -> Hz
(defparameter +aac-sample-rates+
  (make-array 16 :element-type 'fixnum :initial-contents (list 96000 88200 64000 48000 44100 32000 24000 22050 16000 12000 11025 8000 7350 0 0 0)))

;;; Spectral codebooks 1..11: codeword bit patterns and their bit lengths,
;;; indexed by symbol index (ISO 14496-3 Tables 4.A.2..4.A.12 / clause 4.6.3).
(defparameter +aac-spec-codes+
  (vector
   #(#x7f8 #x1f1 #x7fd #x3f5 #x68 #x3f0 #x7f7 #x1ec #x7f5 #x3f1 #x72 #x3f4 #x74 #x11 #x76 #x1eb #x6c #x3f6 #x7fc #x1e1 #x7f1 #x1f0 #x61 #x1f6 #x7f2 #x1ea #x7fb #x1f2 #x69 #x1ed #x77 #x17 #x6f #x1e6 #x64 #x1e5 #x67 #x15 #x62 #x12 #x0 #x14 #x65 #x16 #x6d #x1e9 #x63 #x1e4 #x6b #x13 #x71 #x1e3 #x70 #x1f3 #x7fe #x1e7 #x7f3 #x1ef #x60 #x1ee #x7f0 #x1e2 #x7fa #x3f3 #x6a #x1e8 #x75 #x10 #x73 #x1f4 #x6e #x3f7 #x7f6 #x1e0 #x7f9 #x3f2 #x66 #x1f5 #x7ff #x1f7 #x7f4)
   #(#x1f3 #x6f #x1fd #xeb #x23 #xea #x1f7 #xe8 #x1fa #xf2 #x2d #x70 #x20 #x6 #x2b #x6e #x28 #xe9 #x1f9 #x66 #xf8 #xe7 #x1b #xf1 #x1f4 #x6b #x1f5 #xec #x2a #x6c #x2c #xa #x27 #x67 #x1a #xf5 #x24 #x8 #x1f #x9 #x0 #x7 #x1d #xb #x30 #xef #x1c #x64 #x1e #xc #x29 #xf3 #x2f #xf0 #x1fc #x71 #x1f2 #xf4 #x21 #xe6 #xf7 #x68 #x1f8 #xee #x22 #x65 #x31 #x2 #x26 #xed #x25 #x6a #x1fb #x72 #x1fe #x69 #x2e #xf6 #x1ff #x6d #x1f6)
   #(#x0 #x9 #xef #xb #x19 #xf0 #x1eb #x1e6 #x3f2 #xa #x35 #x1ef #x34 #x37 #x1e9 #x1ed #x1e7 #x3f3 #x1ee #x3ed #x1ffa #x1ec #x1f2 #x7f9 #x7f8 #x3f8 #xff8 #x8 #x38 #x3f6 #x36 #x75 #x3f1 #x3eb #x3ec #xff4 #x18 #x76 #x7f4 #x39 #x74 #x3ef #x1f3 #x1f4 #x7f6 #x1e8 #x3ea #x1ffc #xf2 #x1f1 #xffb #x3f5 #x7f3 #xffc #xee #x3f7 #x7ffe #x1f0 #x7f5 #x7ffd #x1ffb #x3ffa #xffff #xf1 #x3f0 #x3ffc #x1ea #x3ee #x3ffb #xff6 #xffa #x7ffc #x7f2 #xff5 #xfffe #x3f4 #x7f7 #x7ffb #xff7 #xff9 #x7ffa)
   #(#x7 #x16 #xf6 #x18 #x8 #xef #x1ef #xf3 #x7f8 #x19 #x17 #xed #x15 #x1 #xe2 #xf0 #x70 #x3f0 #x1ee #xf1 #x7fa #xee #xe4 #x3f2 #x7f6 #x3ef #x7fd #x5 #x14 #xf2 #x9 #x4 #xe5 #xf4 #xe8 #x3f4 #x6 #x2 #xe7 #x3 #x0 #x6b #xe3 #x69 #x1f3 #xeb #xe6 #x3f6 #x6e #x6a #x1f4 #x3ec #x1f0 #x3f9 #xf5 #xec #x7fb #xea #x6f #x3f7 #x7f9 #x3f3 #xfff #xe9 #x6d #x3f8 #x6c #x68 #x1f5 #x3ee #x1f2 #x7f4 #x7f7 #x3f1 #xffe #x3ed #x1f1 #x7f5 #x7fe #x3f5 #x7fc)
   #(#x1fff #xff7 #x7f4 #x7e8 #x3f1 #x7ee #x7f9 #xff8 #x1ffd #xffd #x7f1 #x3e8 #x1e8 #xf0 #x1ec #x3ee #x7f2 #xffa #xff4 #x3ef #x1f2 #xe8 #x70 #xec #x1f0 #x3ea #x7f3 #x7eb #x1eb #xea #x1a #x8 #x19 #xee #x1ef #x7ed #x3f0 #xf2 #x73 #xb #x0 #xa #x71 #xf3 #x7e9 #x7ef #x1ee #xef #x18 #x9 #x1b #xeb #x1e9 #x7ec #x7f6 #x3eb #x1f3 #xed #x72 #xe9 #x1f1 #x3ed #x7f7 #xff6 #x7f0 #x3e9 #x1ed #xf1 #x1ea #x3ec #x7f8 #xff9 #x1ffc #xffc #xff5 #x7ea #x3f3 #x3f2 #x7f5 #xffb #x1ffe)
   #(#x7fe #x3fd #x1f1 #x1eb #x1f4 #x1ea #x1f0 #x3fc #x7fd #x3f6 #x1e5 #xea #x6c #x71 #x68 #xf0 #x1e6 #x3f7 #x1f3 #xef #x32 #x27 #x28 #x26 #x31 #xeb #x1f7 #x1e8 #x6f #x2e #x8 #x4 #x6 #x29 #x6b #x1ee #x1ef #x72 #x2d #x2 #x0 #x3 #x2f #x73 #x1fa #x1e7 #x6e #x2b #x7 #x1 #x5 #x2c #x6d #x1ec #x1f9 #xee #x30 #x24 #x2a #x25 #x33 #xec #x1f2 #x3f8 #x1e4 #xed #x6a #x70 #x69 #x74 #xf1 #x3fa #x7ff #x3f9 #x1f6 #x1ed #x1f8 #x1e9 #x1f5 #x3fb #x7fc)
   #(#x0 #x5 #x37 #x74 #xf2 #x1eb #x3ed #x7f7 #x4 #xc #x35 #x71 #xec #xee #x1ee #x1f5 #x36 #x34 #x72 #xea #xf1 #x1e9 #x1f3 #x3f5 #x73 #x70 #xeb #xf0 #x1f1 #x1f0 #x3ec #x3fa #xf3 #xed #x1e8 #x1ef #x3ef #x3f1 #x3f9 #x7fb #x1ed #xef #x1ea #x1f2 #x3f3 #x3f8 #x7f9 #x7fc #x3ee #x1ec #x1f4 #x3f4 #x3f7 #x7f8 #xffd #xffe #x7f6 #x3f0 #x3f2 #x3f6 #x7fa #x7fd #xffc #xfff)
   #(#xe #x5 #x10 #x30 #x6f #xf1 #x1fa #x3fe #x3 #x0 #x4 #x12 #x2c #x6a #x75 #xf8 #xf #x2 #x6 #x14 #x2e #x69 #x72 #xf5 #x2f #x11 #x13 #x2a #x32 #x6c #xec #xfa #x71 #x2b #x2d #x31 #x6d #x70 #xf2 #x1f9 #xef #x68 #x33 #x6b #x6e #xee #xf9 #x3fc #x1f8 #x74 #x73 #xed #xf0 #xf6 #x1f6 #x1fd #x3fd #xf3 #xf4 #xf7 #x1f7 #x1fb #x1fc #x3ff)
   #(#x0 #x5 #x37 #xe7 #x1de #x3ce #x3d9 #x7c8 #x7cd #xfc8 #xfdd #x1fe4 #x1fec #x4 #xc #x35 #x72 #xea #xed #x1e2 #x3d1 #x3d3 #x3e0 #x7d8 #xfcf #xfd5 #x36 #x34 #x71 #xe8 #xec #x1e1 #x3cf #x3dd #x3db #x7d0 #xfc7 #xfd4 #xfe4 #xe6 #x70 #xe9 #x1dd #x1e3 #x3d2 #x3dc #x7cc #x7ca #x7de #xfd8 #xfea #x1fdb #x1df #xeb #x1dc #x1e6 #x3d5 #x3de #x7cb #x7dd #x7dc #xfcd #xfe2 #xfe7 #x1fe1 #x3d0 #x1e0 #x1e4 #x3d6 #x7c5 #x7d1 #x7db #xfd2 #x7e0 #xfd9 #xfeb #x1fe3 #x1fe9 #x7c4 #x1e5 #x3d7 #x7c6 #x7cf #x7da #xfcb #xfda #xfe3 #xfe9 #x1fe6 #x1ff3 #x1ff7 #x7d3 #x3d8 #x3e1 #x7d4 #x7d9 #xfd3 #xfde #x1fdd #x1fd9 #x1fe2 #x1fea #x1ff1 #x1ff6 #x7d2 #x3d4 #x3da #x7c7 #x7d7 #x7e2 #xfce #xfdb #x1fd8 #x1fee #x3ff0 #x1ff4 #x3ff2 #x7e1 #x3df #x7c9 #x7d6 #xfca #xfd0 #xfe5 #xfe6 #x1feb #x1fef #x3ff3 #x3ff4 #x3ff5 #xfe0 #x7ce #x7d5 #xfc6 #xfd1 #xfe1 #x1fe0 #x1fe8 #x1ff0 #x3ff1 #x3ff8 #x3ff6 #x7ffc #xfe8 #x7df #xfc9 #xfd7 #xfdc #x1fdc #x1fdf #x1fed #x1ff5 #x3ff9 #x3ffb #x7ffd #x7ffe #x1fe7 #xfcc #xfd6 #xfdf #x1fde #x1fda #x1fe5 #x1ff2 #x3ffa #x3ff7 #x3ffc #x3ffd #x7fff)
   #(#x22 #x8 #x1d #x26 #x5f #xd3 #x1cf #x3d0 #x3d7 #x3ed #x7f0 #x7f6 #xffd #x7 #x0 #x1 #x9 #x20 #x54 #x60 #xd5 #xdc #x1d4 #x3cd #x3de #x7e7 #x1c #x2 #x6 #xc #x1e #x28 #x5b #xcd #xd9 #x1ce #x1dc #x3d9 #x3f1 #x25 #xb #xa #xd #x24 #x57 #x61 #xcc #xdd #x1cc #x1de #x3d3 #x3e7 #x5d #x21 #x1f #x23 #x27 #x59 #x64 #xd8 #xdf #x1d2 #x1e2 #x3dd #x3ee #xd1 #x55 #x29 #x56 #x58 #x62 #xce #xe0 #xe2 #x1da #x3d4 #x3e3 #x7eb #x1c9 #x5e #x5a #x5c #x63 #xca #xda #x1c7 #x1ca #x1e0 #x3db #x3e8 #x7ec #x1e3 #xd2 #xcb #xd0 #xd7 #xdb #x1c6 #x1d5 #x1d8 #x3ca #x3da #x7ea #x7f1 #x1e1 #xd4 #xcf #xd6 #xde #xe1 #x1d0 #x1d6 #x3d1 #x3d5 #x3f2 #x7ee #x7fb #x3e9 #x1cd #x1c8 #x1cb #x1d1 #x1d7 #x1df #x3cf #x3e0 #x3ef #x7e6 #x7f8 #xffa #x3eb #x1dd #x1d3 #x1d9 #x1db #x3d2 #x3cc #x3dc #x3ea #x7ed #x7f3 #x7f9 #xff9 #x7f2 #x3ce #x1e4 #x3cb #x3d8 #x3d6 #x3e2 #x3e5 #x7e8 #x7f4 #x7f5 #x7f7 #xffb #x7fa #x3ec #x3df #x3e1 #x3e4 #x3e6 #x3f0 #x7e9 #x7ef #xff8 #xffe #xffc #xfff)
   #(#x0 #x6 #x19 #x3d #x9c #xc6 #x1a7 #x390 #x3c2 #x3df #x7e6 #x7f3 #xffb #x7ec #xffa #xffe #x38e #x5 #x1 #x8 #x14 #x37 #x42 #x92 #xaf #x191 #x1a5 #x1b5 #x39e #x3c0 #x3a2 #x3cd #x7d6 #xae #x17 #x7 #x9 #x18 #x39 #x40 #x8e #xa3 #xb8 #x199 #x1ac #x1c1 #x3b1 #x396 #x3be #x3ca #x9d #x3c #x15 #x16 #x1a #x3b #x44 #x91 #xa5 #xbe #x196 #x1ae #x1b9 #x3a1 #x391 #x3a5 #x3d5 #x94 #x9a #x36 #x38 #x3a #x41 #x8c #x9b #xb0 #xc3 #x19e #x1ab #x1bc #x39f #x38f #x3a9 #x3cf #x93 #xbf #x3e #x3f #x43 #x45 #x9e #xa7 #xb9 #x194 #x1a2 #x1ba #x1c3 #x3a6 #x3a7 #x3bb #x3d4 #x9f #x1a0 #x8f #x8d #x90 #x98 #xa6 #xb6 #xc4 #x19f #x1af #x1bf #x399 #x3bf #x3b4 #x3c9 #x3e7 #xa8 #x1b6 #xab #xa4 #xaa #xb2 #xc2 #xc5 #x198 #x1a4 #x1b8 #x38c #x3a4 #x3c4 #x3c6 #x3dd #x3e8 #xad #x3af #x192 #xbd #xbc #x18e #x197 #x19a #x1a3 #x1b1 #x38d #x398 #x3b7 #x3d3 #x3d1 #x3db #x7dd #xb4 #x3de #x1a9 #x19b #x19c #x1a1 #x1aa #x1ad #x1b3 #x38b #x3b2 #x3b8 #x3ce #x3e1 #x3e0 #x7d2 #x7e5 #xb7 #x7e3 #x1bb #x1a8 #x1a6 #x1b0 #x1b2 #x1b7 #x39b #x39a #x3ba #x3b5 #x3d6 #x7d7 #x3e4 #x7d8 #x7ea #xba #x7e8 #x3a0 #x1bd #x1b4 #x38a #x1c4 #x392 #x3aa #x3b0 #x3bc #x3d7 #x7d4 #x7dc #x7db #x7d5 #x7f0 #xc1 #x7fb #x3c8 #x3a3 #x395 #x39d #x3ac #x3ae #x3c5 #x3d8 #x3e2 #x3e6 #x7e4 #x7e7 #x7e0 #x7e9 #x7f7 #x190 #x7f2 #x393 #x1be #x1c0 #x394 #x397 #x3ad #x3c3 #x3c1 #x3d2 #x7da #x7d9 #x7df #x7eb #x7f4 #x7fa #x195 #x7f8 #x3bd #x39c #x3ab #x3a8 #x3b3 #x3b9 #x3d0 #x3e3 #x3e5 #x7e2 #x7de #x7ed #x7f1 #x7f9 #x7fc #x193 #xffd #x3dc #x3b6 #x3c7 #x3cc #x3cb #x3d9 #x3da #x7d3 #x7e1 #x7ee #x7ef #x7f5 #x7f6 #xffc #xfff #x19d #x1c2 #xb5 #xa1 #x96 #x97 #x95 #x99 #xa0 #xa2 #xac #xa9 #xb1 #xb3 #xbb #xc0 #x18f #x4)
  ))

(defparameter +aac-spec-bits+
  (vector
   #(11 9 11 10 7 10 11 9 11 10 7 10 7 5 7 9 7 10 11 9 11 9 7 9 11 9 11 9 7 9 7 5 7 9 7 9 7 5 7 5 1 5 7 5 7 9 7 9 7 5 7 9 7 9 11 9 11 9 7 9 11 9 11 10 7 9 7 5 7 9 7 10 11 9 11 10 7 9 11 9 11)
   #(9 7 9 8 6 8 9 8 9 8 6 7 6 5 6 7 6 8 9 7 8 8 6 8 9 7 9 8 6 7 6 5 6 7 6 8 6 5 6 5 3 5 6 5 6 8 6 7 6 5 6 8 6 8 9 7 9 8 6 8 8 7 9 8 6 7 6 4 6 8 6 7 9 7 9 7 6 8 9 7 9)
   #(1 4 8 4 5 8 9 9 10 4 6 9 6 6 9 9 9 10 9 10 13 9 9 11 11 10 12 4 6 10 6 7 10 10 10 12 5 7 11 6 7 10 9 9 11 9 10 13 8 9 12 10 11 12 8 10 15 9 11 15 13 14 16 8 10 14 9 10 14 12 12 15 11 12 16 10 11 15 12 12 15)
   #(4 5 8 5 4 8 9 8 11 5 5 8 5 4 8 8 7 10 9 8 11 8 8 10 11 10 11 4 5 8 4 4 8 8 8 10 4 4 8 4 4 7 8 7 9 8 8 10 7 7 9 10 9 10 8 8 11 8 7 10 11 10 12 8 7 10 7 7 9 10 9 11 11 10 12 10 9 11 11 10 11)
   #(13 12 11 11 10 11 11 12 13 12 11 10 9 8 9 10 11 12 12 10 9 8 7 8 9 10 11 11 9 8 5 4 5 8 9 11 10 8 7 4 1 4 7 8 11 11 9 8 5 4 5 8 9 11 11 10 9 8 7 8 9 10 11 12 11 10 9 8 9 10 11 12 13 12 12 11 10 10 11 12 13)
   #(11 10 9 9 9 9 9 10 11 10 9 8 7 7 7 8 9 10 9 8 6 6 6 6 6 8 9 9 7 6 4 4 4 6 7 9 9 7 6 4 4 4 6 7 9 9 7 6 4 4 4 6 7 9 9 8 6 6 6 6 6 8 9 10 9 8 7 7 7 7 8 10 11 10 9 9 9 9 9 10 11)
   #(1 3 6 7 8 9 10 11 3 4 6 7 8 8 9 9 6 6 7 8 8 9 9 10 7 7 8 8 9 9 10 10 8 8 9 9 10 10 10 11 9 8 9 9 10 10 11 11 10 9 9 10 10 11 12 12 11 10 10 10 11 11 12 12)
   #(5 4 5 6 7 8 9 10 4 3 4 5 6 7 7 8 5 4 4 5 6 7 7 8 6 5 5 6 6 7 8 8 7 6 6 6 7 7 8 9 8 7 6 7 7 8 8 10 9 7 7 8 8 8 9 9 10 8 8 8 9 9 9 10)
   #(1 3 6 8 9 10 10 11 11 12 12 13 13 3 4 6 7 8 8 9 10 10 10 11 12 12 6 6 7 8 8 9 10 10 10 11 12 12 12 8 7 8 9 9 10 10 11 11 11 12 12 13 9 8 9 9 10 10 11 11 11 12 12 12 13 10 9 9 10 11 11 11 12 11 12 12 13 13 11 9 10 11 11 11 12 12 12 12 13 13 13 11 10 10 11 11 12 12 13 13 13 13 13 13 11 10 10 11 11 11 12 12 13 13 14 13 14 11 10 11 11 12 12 12 12 13 13 14 14 14 12 11 11 12 12 12 13 13 13 14 14 14 15 12 11 12 12 12 13 13 13 13 14 14 15 15 13 12 12 12 13 13 13 13 14 14 14 14 15)
   #(6 5 6 6 7 8 9 10 10 10 11 11 12 5 4 4 5 6 7 7 8 8 9 10 10 11 6 4 5 5 6 6 7 8 8 9 9 10 10 6 5 5 5 6 7 7 8 8 9 9 10 10 7 6 6 6 6 7 7 8 8 9 9 10 10 8 7 6 7 7 7 8 8 8 9 10 10 11 9 7 7 7 7 8 8 9 9 9 10 10 11 9 8 8 8 8 8 9 9 9 10 10 11 11 9 8 8 8 8 8 9 9 10 10 10 11 11 10 9 9 9 9 9 9 10 10 10 11 11 12 10 9 9 9 9 10 10 10 10 11 11 11 12 11 10 9 10 10 10 10 10 11 11 11 11 12 11 10 10 10 10 10 10 11 11 12 12 12 12)
   #(4 5 6 7 8 8 9 10 10 10 11 11 12 11 12 12 10 5 4 5 6 7 7 8 8 9 9 9 10 10 10 10 11 8 6 5 5 6 7 7 8 8 8 9 9 9 10 10 10 10 8 7 6 6 6 7 7 8 8 8 9 9 9 10 10 10 10 8 8 7 7 7 7 8 8 8 8 9 9 9 10 10 10 10 8 8 7 7 7 7 8 8 8 9 9 9 9 10 10 10 10 8 9 8 8 8 8 8 8 8 9 9 9 10 10 10 10 10 8 9 8 8 8 8 8 8 9 9 9 10 10 10 10 10 10 8 10 9 8 8 9 9 9 9 9 10 10 10 10 10 10 11 8 10 9 9 9 9 9 9 9 10 10 10 10 10 10 11 11 8 11 9 9 9 9 9 9 10 10 10 10 10 11 10 11 11 8 11 10 9 9 10 9 10 10 10 10 10 11 11 11 11 11 8 11 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11 9 11 10 9 9 10 10 10 10 10 10 11 11 11 11 11 11 9 11 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11 9 12 10 10 10 10 10 10 10 11 11 11 11 11 11 12 12 9 9 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 5)
  ))

;;; Per-codebook: (dimension unsigned-p modulo offset escape-p)
(defparameter +aac-cb-params+
  (vector
   #(4 0 3 1 0)
   #(4 0 3 1 0)
   #(4 1 3 0 0)
   #(4 1 3 0 0)
   #(2 0 9 4 0)
   #(2 0 9 4 0)
   #(2 1 8 0 0)
   #(2 1 8 0 0)
   #(2 1 13 0 0)
   #(2 1 13 0 0)
   #(2 1 17 0 1)
  ))

;;; Differential scalefactor Huffman codebook (121 entries, symbol-60 = delta)
(defparameter +aac-sf-codes+ #(#x3ffe8 #x3ffe6 #x3ffe7 #x3ffe5 #x7fff5 #x7fff1 #x7ffed #x7fff6 #x7ffee #x7ffef #x7fff0 #x7fffc #x7fffd #x7ffff #x7fffe #x7fff7 #x7fff8 #x7fffb #x7fff9 #x3ffe4 #x7fffa #x3ffe3 #x1ffef #x1fff0 #xfff5 #x1ffee #xfff2 #xfff3 #xfff4 #xfff1 #x7ff6 #x7ff7 #x3ff9 #x3ff5 #x3ff7 #x3ff3 #x3ff6 #x3ff2 #x1ff7 #x1ff5 #xff9 #xff7 #xff6 #x7f9 #xff4 #x7f8 #x3f9 #x3f7 #x3f5 #x1f8 #x1f7 #xfa #xf8 #xf6 #x79 #x3a #x38 #x1a #xb #x4 #x0 #xa #xc #x1b #x39 #x3b #x78 #x7a #xf7 #xf9 #x1f6 #x1f9 #x3f4 #x3f6 #x3f8 #x7f5 #x7f4 #x7f6 #x7f7 #xff5 #xff8 #x1ff4 #x1ff6 #x1ff8 #x3ff8 #x3ff4 #xfff0 #x7ff4 #xfff6 #x7ff5 #x3ffe2 #x7ffd9 #x7ffda #x7ffdb #x7ffdc #x7ffdd #x7ffde #x7ffd8 #x7ffd2 #x7ffd3 #x7ffd4 #x7ffd5 #x7ffd6 #x7fff2 #x7ffdf #x7ffe7 #x7ffe8 #x7ffe9 #x7ffea #x7ffeb #x7ffe6 #x7ffe0 #x7ffe1 #x7ffe2 #x7ffe3 #x7ffe4 #x7ffe5 #x7ffd7 #x7ffec #x7fff4 #x7fff3))
(defparameter +aac-sf-bits+  #(18 18 18 18 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 18 19 18 17 17 16 17 16 16 16 16 15 15 14 14 14 14 14 14 13 13 12 12 12 11 12 11 10 10 10 9 9 8 8 8 7 6 6 5 4 3 1 4 4 5 6 6 7 7 8 8 9 9 10 10 10 11 11 11 11 12 12 13 13 13 14 14 16 15 16 15 18 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19))

;;; Scalefactor window band offsets per sampling-frequency index (0..12).
;;; Last entry of each vector is the transform length (1024 / 128).
(defparameter +aac-swb-1024+
  (vector
   #(0 4 8 12 16 20 24 28 32 36 40 44 48 52 56 64 72 80 88 96 108 120 132 144 156 172 188 212 240 276 320 384 448 512 576 640 704 768 832 896 960 1024)
   #(0 4 8 12 16 20 24 28 32 36 40 44 48 52 56 64 72 80 88 96 108 120 132 144 156 172 188 212 240 276 320 384 448 512 576 640 704 768 832 896 960 1024)
   #(0 4 8 12 16 20 24 28 32 36 40 44 48 52 56 64 72 80 88 100 112 124 140 156 172 192 216 240 268 304 344 384 424 464 504 544 584 624 664 704 744 784 824 864 904 944 984 1024)
   #(0 4 8 12 16 20 24 28 32 36 40 48 56 64 72 80 88 96 108 120 132 144 160 176 196 216 240 264 292 320 352 384 416 448 480 512 544 576 608 640 672 704 736 768 800 832 864 896 928 1024)
   #(0 4 8 12 16 20 24 28 32 36 40 48 56 64 72 80 88 96 108 120 132 144 160 176 196 216 240 264 292 320 352 384 416 448 480 512 544 576 608 640 672 704 736 768 800 832 864 896 928 1024)
   #(0 4 8 12 16 20 24 28 32 36 40 48 56 64 72 80 88 96 108 120 132 144 160 176 196 216 240 264 292 320 352 384 416 448 480 512 544 576 608 640 672 704 736 768 800 832 864 896 928 960 992 1024)
   #(0 4 8 12 16 20 24 28 32 36 40 44 52 60 68 76 84 92 100 108 116 124 136 148 160 172 188 204 220 240 260 284 308 336 364 396 432 468 508 552 600 652 704 768 832 896 960 1024)
   #(0 4 8 12 16 20 24 28 32 36 40 44 52 60 68 76 84 92 100 108 116 124 136 148 160 172 188 204 220 240 260 284 308 336 364 396 432 468 508 552 600 652 704 768 832 896 960 1024)
   #(0 8 16 24 32 40 48 56 64 72 80 88 100 112 124 136 148 160 172 184 196 212 228 244 260 280 300 320 344 368 396 424 456 492 532 572 616 664 716 772 832 896 960 1024)
   #(0 8 16 24 32 40 48 56 64 72 80 88 100 112 124 136 148 160 172 184 196 212 228 244 260 280 300 320 344 368 396 424 456 492 532 572 616 664 716 772 832 896 960 1024)
   #(0 8 16 24 32 40 48 56 64 72 80 88 100 112 124 136 148 160 172 184 196 212 228 244 260 280 300 320 344 368 396 424 456 492 532 572 616 664 716 772 832 896 960 1024)
   #(0 12 24 36 48 60 72 84 96 108 120 132 144 156 172 188 204 220 236 252 268 288 308 328 348 372 396 420 448 476 508 544 580 620 664 712 764 820 880 944 1024)
   #(0 12 24 36 48 60 72 84 96 108 120 132 144 156 172 188 204 220 236 252 268 288 308 328 348 372 396 420 448 476 508 544 580 620 664 712 764 820 880 944 1024)
  ))

(defparameter +aac-swb-128+
  (vector
   #(0 4 8 12 16 20 24 32 40 48 64 92 128)
   #(0 4 8 12 16 20 24 32 40 48 64 92 128)
   #(0 4 8 12 16 20 24 32 40 48 64 92 128)
   #(0 4 8 12 16 20 28 36 44 56 68 80 96 112 128)
   #(0 4 8 12 16 20 28 36 44 56 68 80 96 112 128)
   #(0 4 8 12 16 20 28 36 44 56 68 80 96 112 128)
   #(0 4 8 12 16 20 24 28 36 44 52 64 76 92 108 128)
   #(0 4 8 12 16 20 24 28 36 44 52 64 76 92 108 128)
   #(0 4 8 12 16 20 24 28 32 40 48 60 72 88 108 128)
   #(0 4 8 12 16 20 24 28 32 40 48 60 72 88 108 128)
   #(0 4 8 12 16 20 24 28 32 40 48 60 72 88 108 128)
   #(0 4 8 12 16 20 24 28 36 44 52 60 72 88 108 128)
   #(0 4 8 12 16 20 24 28 36 44 52 60 72 88 108 128)
  ))

(defparameter +aac-tns-max-bands-1024+ #(31 31 34 40 42 51 46 46 42 42 42 39 39))
(defparameter +aac-tns-max-bands-128+  #(9 9 10 14 14 14 14 14 14 14 14 14 14))

;;; TNS quantized-coef -> reflection(parcor) coefficient; index 2*compress+res
(defparameter +aac-tns-tmp2-map+
  (vector
   (make-array 8 :element-type 'double-float :initial-contents '(0.00000000d0 -0.43388373d0 -0.78183150d0 -0.97492790d0 0.98480773d0 0.86602539d0 0.64278758d0 0.34202015d0))
   (make-array 16 :element-type 'double-float :initial-contents '(0.00000000d0 -0.20791170d0 -0.40673664d0 -0.58778524d0 -0.74314481d0 -0.86602539d0 -0.95105654d0 -0.99452192d0 0.99573416d0 0.96182561d0 0.89516330d0 0.79801720d0 0.67369562d0 0.52643216d0 0.36124167d0 0.18374951d0))
   (make-array 4 :element-type 'double-float :initial-contents '(0.00000000d0 -0.43388373d0 0.64278758d0 0.34202015d0))
   (make-array 8 :element-type 'double-float :initial-contents '(0.00000000d0 -0.20791170d0 -0.40673664d0 -0.58778524d0 0.67369562d0 0.52643216d0 0.36124167d0 0.18374951d0))
  ))
