;;;; src/opus/celt.lisp — the CELT decoder (RFC 6716 §4.3), CELT-only path.
;;;;
;;;; A faithful float port of libopus celt/{celt_decoder,bands,rate,vq,cwrs,
;;;; quant_bands,celt}.c for the standard 48 kHz Opus CELT mode (21 bands,
;;;; shortMdctSize 120, maxLM 3, overlap 120).  Decoder side only: the encoder,
;;;; theta-RDO and resynthesis-conditional branches are dropped (resynth is
;;;; always on when decoding).  Spectral vectors (celt_norm) and time/signal
;;;; buffers (celt_sig) are double-float arrays; entropy state is the ec-dec
;;;; from range.lisp.  All the Q-macro fixed-point scaling collapses to plain
;;;; float arithmetic (Q15ONE=1, shifts are identity), matching arch.h float.
(in-package #:reed)

(deftype f64vec () '(simple-array double-float (*)))
(declaim (inline f64vec mkf64))
(defun mkf64 (n) (make-array n :element-type 'double-float :initial-element 0d0))


(defconstant +celt-decode-buffer-size+ 2048)
(defconstant +celt-lpc-order+ 24)
(defconstant +combfilter-minperiod+ 15)
(defconstant +celt-bitres+ 3)
(defconstant +celt-max-fine-bits+ 8)
(defconstant +celt-qtheta-offset+ 4)
(defconstant +celt-qtheta-offset-twophase+ 16)
(defconstant +celt-fine-offset+ 21)

;;; ==== bit-exact scalar helpers (bands.c / mathops.h) =====================
(declaim (inline frac-mul16 bitexact-cos bitexact-log2tan celt-lcg-rand))
(defun frac-mul16 (a b) (ash (+ 16384 (* a b)) -15))

(defun bitexact-cos (x)
  (let* ((tmp (ash (+ 4096 (* x x)) -13))
         (x2 tmp))
    (setf x2 (+ (- 32767 x2)
                (frac-mul16 x2 (+ -7651 (frac-mul16 x2 (+ 8277 (frac-mul16 -626 x2)))))))
    (+ 1 x2)))

(defun bitexact-log2tan (isin icos)
  (let ((lc (integer-length icos))
        (ls (integer-length isin)))
    (setf icos (ash icos (- 15 lc))
          isin (ash isin (- 15 ls)))
    (+ (* (- ls lc) 2048)
       (frac-mul16 isin (+ (frac-mul16 isin -2597) 7932))
       (- (frac-mul16 icos (+ (frac-mul16 icos -2597) 7932))))))

(defun celt-lcg-rand (seed) (logand (+ (* 1664525 seed) 1013904223) +u32+))

;;; ==== CWRS pulse-vector deindexing (cwrs.c, non-small-footprint) =========
(defun %unext (u off len ui0)
  (declare (type (simple-array (unsigned-byte 32) (*)) u))
  (loop for j from 1 below len do
    (let ((ui1 (logand (+ (aref u (+ off j)) (aref u (+ off (1- j))) ui0) +u32+)))
      (setf (aref u (+ off (1- j))) ui0 ui0 ui1)))
  (setf (aref u (+ off (1- len))) ui0))

(defun %uprev (u n ui0)
  (declare (type (simple-array (unsigned-byte 32) (*)) u))
  (loop for j from 1 below n do
    (let ((ui1 (logand (- (aref u j) (aref u (1- j)) ui0) +u32+)))
      (setf (aref u (1- j)) ui0 ui0 ui1)))
  (setf (aref u (1- n)) ui0))

(defun %ncwrs-urow (n k u)
  "Fill u[0..k+1] with U(n,·); return V(n,k)=U(n,k)+U(n,k+1)."
  (declare (type (simple-array (unsigned-byte 32) (*)) u))
  (setf (aref u 0) 0 (aref u 1) 1)
  (loop for kk from 2 below (+ k 2) do (setf (aref u kk) (logand (1- (* kk 2)) +u32+)))
  (loop for kk from 2 below n do (%unext u 1 (1+ k) 1))
  (logand (+ (aref u k) (aref u (1+ k))) +u32+))

(defun %cwrsi (n k i y yoff u)
  "Decode the i'th length-n unit pulse vector with k pulses into y[yoff..]."
  (declare (type (simple-array (unsigned-byte 32) (*)) u) (type fixnum n k))
  (let ((yy 0) (i (logand i +u32+)))
    (dotimes (j n)
      (let* ((p (aref u (1+ k)))
             (s (if (>= i p) -1 0)))
        (when (= s -1) (setf i (logand (- i p) +u32+)))
        (let ((yj k))
          (setf p (aref u k))
          (loop while (> p i) do (setf p (aref u (decf k))))
          (setf i (logand (- i p) +u32+))
          (decf yj k)
          (let ((val (logxor (+ yj s) s)))
            (setf (aref y (+ yoff j)) val)
            (incf yy (* val val))))
        (%uprev u (+ k 2) 0)))
    yy))

(defun decode-pulses (y yoff n k dec)
  (let ((u (make-array (+ k 2) :element-type '(unsigned-byte 32) :initial-element 0)))
    (let ((v (%ncwrs-urow n k u)))
      (%cwrsi n k (ec-dec-uint dec v) y yoff u))))

;;; ==== VQ: rotation, normalisation, collapse mask (vq.c) ==================
(defun %exp-rotation1 (x xoff len stride c s)
  (declare (type f64vec x))
  (let ((ms (- s)))
    (loop for i from 0 below (- len stride) do
      (let ((x1 (aref x (+ xoff i)))
            (x2 (aref x (+ xoff i stride))))
        (setf (aref x (+ xoff i stride)) (+ (* c x2) (* s x1))
              (aref x (+ xoff i)) (+ (* c x1) (* ms x2)))))
    (loop for i from (- len (* 2 stride) 1) downto 0 do
      (let ((x1 (aref x (+ xoff i)))
            (x2 (aref x (+ xoff i stride))))
        (setf (aref x (+ xoff i stride)) (+ (* c x2) (* s x1))
              (aref x (+ xoff i)) (+ (* c x1) (* ms x2)))))))

(defun exp-rotation (x xoff len dir stride k spread)
  (declare (type f64vec x))
  (when (or (>= (* 2 k) len) (= spread 0)) (return-from exp-rotation))
  (let* ((factor (aref #(15 10 5) (1- spread)))
         (gain (/ (float len 1d0) (+ len (* factor k))))
         (theta (* 0.5d0 gain gain))
         (c (cos (* 0.5d0 pi theta)))
         (s (cos (* 0.5d0 pi (- 1d0 theta))))   ; = sin(0.5*pi*theta)
         (stride2 0))
    (when (>= len (* 8 stride))
      (setf stride2 1)
      (loop while (< (+ (* (+ (* stride2 stride2) stride2) stride) (ash stride -2)) len)
            do (incf stride2)))
    (let ((len2 (floor len stride)))
      (dotimes (i stride)
        (let ((off (+ xoff (* i len2))))
          (if (< dir 0)
              (progn
                (when (/= stride2 0) (%exp-rotation1 x off len2 stride2 s c))
                (%exp-rotation1 x off len2 1 c s))
              (progn
                (%exp-rotation1 x off len2 1 c (- s))
                (when (/= stride2 0) (%exp-rotation1 x off len2 stride2 s (- c))))))))))

(defun %normalise-residual (iy x xoff n ryy gain)
  (declare (type f64vec x) (type (simple-array (signed-byte 32) (*)) iy))
  (let ((g (/ gain (sqrt (float ryy 1d0)))))
    (dotimes (i n) (setf (aref x (+ xoff i)) (* g (aref iy i))))))

(defun %extract-collapse-mask (iy n b)
  (declare (type (simple-array (signed-byte 32) (*)) iy))
  (if (<= b 1) 1
      (let ((n0 (floor n b)) (cm 0))
        (dotimes (i b)
          (let ((tmp 0))
            (dotimes (j n0) (setf tmp (logior tmp (abs (aref iy (+ (* i n0) j))))))
            (setf cm (logior cm (ash (if (/= tmp 0) 1 0) i)))))
        cm)))

(defun alg-unquant (x xoff n k spread b dec gain)
  (declare (type f64vec x))
  (let* ((iy (make-array n :element-type '(signed-byte 32) :initial-element 0))
         (ryy (decode-pulses iy 0 n k dec)))
    (%normalise-residual iy x xoff n ryy gain)
    (exp-rotation x xoff n -1 b k spread)
    (%extract-collapse-mask iy n b)))

(defun renormalise-vector (x xoff n gain)
  (declare (type f64vec x))
  (let ((e 1d-15))
    (dotimes (i n) (incf e (* (aref x (+ xoff i)) (aref x (+ xoff i)))))
    (let ((g (/ gain (sqrt e))))
      (dotimes (i n) (setf (aref x (+ xoff i)) (* g (aref x (+ xoff i))))))))

;;; ==== stereo / Hadamard ops (bands.c) ===================================
(defconstant +sqrt1/2+ 0.7071067811865476d0)

(defun stereo-split (x xoff y yoff n)
  (declare (type f64vec x y))
  (dotimes (j n)
    (let ((l (* +sqrt1/2+ (aref x (+ xoff j))))
          (r (* +sqrt1/2+ (aref y (+ yoff j)))))
      (setf (aref x (+ xoff j)) (+ l r)
            (aref y (+ yoff j)) (- r l)))))

(defun stereo-merge (x xoff y yoff mid n)
  (declare (type f64vec x y))
  (let ((xp 0d0) (side 0d0))
    (dotimes (j n)
      (incf xp (* (aref y (+ yoff j)) (aref x (+ xoff j))))
      (incf side (* (aref y (+ yoff j)) (aref y (+ yoff j)))))
    (setf xp (* mid xp))
    (let* ((mid2 mid)
           (el (+ (* mid2 mid2) side (* -2d0 xp)))
           (er (+ (* mid2 mid2) side (* 2d0 xp))))
      (if (or (< er 6d-4) (< el 6d-4))
          (dotimes (j n) (setf (aref y (+ yoff j)) (aref x (+ xoff j))))
          (let ((lgain (/ 1d0 (sqrt el))) (rgain (/ 1d0 (sqrt er))))
            (dotimes (j n)
              (let ((l (* mid (aref x (+ xoff j))))
                    (r (aref y (+ yoff j))))
                (setf (aref x (+ xoff j)) (* lgain (- l r))
                      (aref y (+ yoff j)) (* rgain (+ l r))))))))))

(defun haar1 (x xoff n0 stride)
  (declare (type f64vec x))
  (let ((n0h (ash n0 -1)))
    (dotimes (i stride)
      (dotimes (j n0h)
        (let* ((a (+ xoff (* stride 2 j) i))
               (b (+ xoff (* stride (1+ (* 2 j))) i))
               (t1 (* +sqrt1/2+ (aref x a)))
               (t2 (* +sqrt1/2+ (aref x b))))
          (setf (aref x a) (+ t1 t2) (aref x b) (- t1 t2)))))))

(defparameter +ordery-table+
  #(1 0
    3 0 2 1
    7 0 4 3 6 1 5 2
    15 0 8 7 12 3 11 4 14 1 9 6 13 2 10 5))

(defun deinterleave-hadamard (x xoff n0 stride hadamard)
  (declare (type f64vec x))
  (let* ((n (* n0 stride)) (tmp (mkf64 n)))
    (if hadamard
        (let ((ob (- stride 2)))
          (dotimes (i stride)
            (dotimes (j n0)
              (setf (aref tmp (+ (* (aref +ordery-table+ (+ ob i)) n0) j))
                    (aref x (+ xoff (* j stride) i))))))
        (dotimes (i stride)
          (dotimes (j n0)
            (setf (aref tmp (+ (* i n0) j)) (aref x (+ xoff (* j stride) i))))))
    (dotimes (i n) (setf (aref x (+ xoff i)) (aref tmp i)))))

(defun interleave-hadamard (x xoff n0 stride hadamard)
  (declare (type f64vec x))
  (let* ((n (* n0 stride)) (tmp (mkf64 n)))
    (if hadamard
        (let ((ob (- stride 2)))
          (dotimes (i stride)
            (dotimes (j n0)
              (setf (aref tmp (+ (* j stride) i))
                    (aref x (+ xoff (* (aref +ordery-table+ (+ ob i)) n0) j))))))
        (dotimes (i stride)
          (dotimes (j n0)
            (setf (aref tmp (+ (* j stride) i)) (aref x (+ xoff (* i n0) j))))))
    (dotimes (i n) (setf (aref x (+ xoff i)) (aref tmp i)))))

(defparameter +bit-interleave-table+ #(0 1 1 1 2 3 3 3 2 3 3 3 2 3 3 3))
(defparameter +bit-deinterleave-table+
  #(#x00 #x03 #x0C #x0F #x30 #x33 #x3C #x3F #xC0 #xC3 #xCC #xCF #xF0 #xF3 #xFC #xFF))

;;; ==== band context ======================================================
(defstruct (bctx (:constructor make-bctx))
  dec (i 0 :type fixnum) (intensity 0 :type fixnum) (spread 2 :type fixnum)
  (tf-change 0 :type fixnum) (remaining-bits 0 :type fixnum) (seed 0 :type fixnum)
  (disable-inv 0 :type fixnum))

(declaim (inline %logn %cache-off))
(defun %logn (i) (aref +celt-logn+ i))
(defun %cache-off (lm-idx band) (aref +celt-cache-index+ (+ (* lm-idx +celt-nbebands+) band)))

;;; ==== rate.c: pulse<->bits ==============================================
(declaim (inline get-pulses))
(defun get-pulses (i) (if (< i 8) i (ash (+ 8 (logand i 7)) (- (ash i -3) 1))))

(defun bits2pulses (band lm bits)
  (let* ((cb (%cache-off (1+ lm) band))
         (lo 0) (hi (aref +celt-cache-bits+ cb)))
    (decf bits)
    (dotimes (i 6)
      (let ((mid (ash (+ lo hi 1) -1)))
        (if (>= (aref +celt-cache-bits+ (+ cb mid)) bits) (setf hi mid) (setf lo mid))))
    (if (<= (- bits (if (= lo 0) -1 (aref +celt-cache-bits+ (+ cb lo))))
            (- (aref +celt-cache-bits+ (+ cb hi)) bits))
        lo hi)))

(defun pulses2bits (band lm pulses)
  (if (= pulses 0) 0
      (1+ (aref +celt-cache-bits+ (+ (%cache-off (1+ lm) band) pulses)))))

;;; ==== compute_qn / compute_theta (bands.c) ==============================
(defun compute-qn (n b offset pulse-cap stereo)
  (let ((n2 (- (* 2 n) 1)))
    (when (and stereo (= n 2)) (decf n2))
    (let ((qb (truncate (+ b (* n2 offset)) n2)))
      (setf qb (min (- b pulse-cap (ash 4 +celt-bitres+)) qb))
      (setf qb (min (ash 8 +celt-bitres+) qb))
      (if (< qb (ash (ash 1 +celt-bitres+) -1))
          1
          (let ((qn (ash (aref +celt-exp2-table8+ (logand qb 7)) (- (- 14 (ash qb (- +celt-bitres+)))))))
            (ash (ash (1+ qn) -1) 1))))))

(defun compute-theta (ctx x xoff y yoff n b bb b0 lm stereo fill)
  "Decoder compute_theta. Returns (values b inv imid iside delta itheta qalloc fill)."
  (let* ((i (bctx-i ctx))
         (dec (bctx-dec ctx))
         (pulse-cap (+ (%logn i) (* lm (ash 1 +celt-bitres+))))
         (offset (- (ash pulse-cap -1)
                    (if (and stereo (= n 2)) +celt-qtheta-offset-twophase+ +celt-qtheta-offset+)))
         (qn (compute-qn n b offset pulse-cap stereo))
         (itheta 0) (inv 0) (imid 0) (iside 0) (delta 0)
         (tell (ec-tell-frac dec)))
    (when (and stereo (>= i (bctx-intensity ctx))) (setf qn 1))
    (cond
      ((/= qn 1)
       (cond
         ((and stereo (> n 2))
          (let* ((p0 3) (x0 (ash qn -1)) (ft (+ (* p0 (1+ x0)) x0))
                 (fs (ec-decode dec ft)) (xx 0))
            (if (< fs (* (1+ x0) p0)) (setf xx (floor fs p0))
                (setf xx (+ x0 1 (- fs (* (1+ x0) p0)))))
            (ec-dec-update dec
                           (if (<= xx x0) (* p0 xx) (+ (- xx 1 x0) (* (1+ x0) p0)))
                           (if (<= xx x0) (* p0 (1+ xx)) (+ (- xx x0) (* (1+ x0) p0)))
                           ft)
            (setf itheta xx)))
         ((or (> b0 1) stereo)
          (setf itheta (ec-dec-uint dec (1+ qn))))
         (t
          (let* ((ft (* (1+ (ash qn -1)) (1+ (ash qn -1))))
                 (fm (ec-decode dec ft)) (fl 0) (fs 1))
            (if (< fm (ash (* (ash qn -1) (1+ (ash qn -1))) -1))
                (progn (setf itheta (ash (- (isqrt (+ (* 8 fm) 1)) 1) -1)
                             fs (1+ itheta) fl (ash (* itheta (1+ itheta)) -1)))
                (progn (setf itheta (ash (- (* 2 (1+ qn)) (isqrt (+ (* 8 (- ft fm 1)) 1))) -1)
                             fs (- (1+ qn) itheta)
                             fl (- ft (ash (* (- (1+ qn) itheta) (- (+ 2 qn) itheta)) -1)))))
            (ec-dec-update dec fl (+ fl fs) ft))))
       (setf itheta (floor (* itheta 16384) qn)))
      (stereo
       (if (and (> b (ash 2 +celt-bitres+)) (> (bctx-remaining-bits ctx) (ash 2 +celt-bitres+)))
           (setf inv (ec-dec-bit-logp dec 2))
           (setf inv 0))
       (when (/= (bctx-disable-inv ctx) 0) (setf inv 0))
       (setf itheta 0)))
    (let ((qalloc (- (ec-tell-frac dec) tell)))
      (decf b qalloc)
      (cond
        ((= itheta 0) (setf imid 32767 iside 0 fill (logand fill (1- (ash 1 bb))) delta -16384))
        ((= itheta 16384) (setf imid 0 iside 32767 fill (logand fill (ash (1- (ash 1 bb)) bb)) delta 16384))
        (t (setf imid (bitexact-cos itheta)
                 iside (bitexact-cos (- 16384 itheta))
                 delta (frac-mul16 (ash (- n 1) 7) (bitexact-log2tan iside imid)))))
      (values b inv imid iside delta itheta qalloc fill))))

;;; ==== quant_band_n1 / quant_partition / quant_band / stereo =============
(defun quant-band-n1 (ctx x xoff y yoff lbo lbooff)
  (declare (type f64vec x))
  (let ((dec (bctx-dec ctx)) (stereo (not (null y))))
    (dotimes (c (if stereo 2 1))
      (let ((sign 0) (xx (if (= c 0) x y)) (xxo (if (= c 0) xoff yoff)))
        (when (>= (bctx-remaining-bits ctx) (ash 1 +celt-bitres+))
          (setf sign (ec-dec-bits dec 1))
          (decf (bctx-remaining-bits ctx) (ash 1 +celt-bitres+)))
        (setf (aref xx xxo) (if (/= sign 0) -1d0 1d0))))
    ;; libopus: lowband_out[0]=SHR16(X[0],4); in FLOAT mode SHR16 is identity.
    (when lbo (setf (aref lbo lbooff) (aref x xoff)))
    1))

(defun quant-partition (ctx x xoff n b bb lowband lboff lm gain fill)
  (declare (type f64vec x))
  (let* ((dec (bctx-dec ctx)) (i (bctx-i ctx)) (spread (bctx-spread ctx))
         (cb (%cache-off (1+ lm) i)) (b0 bb) (cm 0))
    (if (and (/= lm -1) (> b (+ (aref +celt-cache-bits+ (+ cb (aref +celt-cache-bits+ cb))) 12)) (> n 2))
        (let ((n2 (ash n -1)) (y-off (+ xoff (ash n -1))) (lm2 (1- lm)) (bb2 bb) fill2)
          (when (= bb 1) (setf fill (logior (logand fill 1) (ash fill 1))))
          (setf bb2 (ash (1+ bb) -1))
          (multiple-value-bind (nb inv imid iside delta itheta qalloc nfill)
              (compute-theta ctx x xoff x y-off n2 b bb2 b0 lm2 nil fill)
            (declare (ignore inv))
            (setf b nb fill nfill)
            (let ((mid (* (/ 1d0 32768) imid)) (side (* (/ 1d0 32768) iside))
                  (next-lb2 (and lowband (+ lboff n2))))
              (when (and (> b0 1) (/= (logand itheta #x3fff) 0))
                (if (> itheta 8192)
                    (decf delta (ash delta (- (- 4 lm2))))
                    (setf delta (min 0 (+ delta (ash (ash n2 +celt-bitres+) (- (- 5 lm2))))))))
              (let ((mbits (max 0 (min b (floor (- b delta) 2)))) (sbits 0) (rebalance 0))
                (setf sbits (- b mbits))
                (decf (bctx-remaining-bits ctx) qalloc)
                (setf rebalance (bctx-remaining-bits ctx))
                (if (>= mbits sbits)
                    (progn
                      (setf cm (quant-partition ctx x xoff n2 mbits bb2 lowband lboff lm2 (* gain mid) fill))
                      (setf rebalance (- mbits (- rebalance (bctx-remaining-bits ctx))))
                      (when (and (> rebalance (ash 3 +celt-bitres+)) (/= itheta 0))
                        (incf sbits (- rebalance (ash 3 +celt-bitres+))))
                      (setf cm (logior cm (ash (quant-partition ctx x y-off n2 sbits bb2 lowband
                                                                (and next-lb2 next-lb2) lm2 (* gain side) (ash fill (- bb2)))
                                               (ash b0 -1)))))
                    (progn
                      (setf cm (ash (quant-partition ctx x y-off n2 sbits bb2 lowband
                                                     (and next-lb2 next-lb2) lm2 (* gain side) (ash fill (- bb2)))
                                    (ash b0 -1)))
                      (setf rebalance (- sbits (- rebalance (bctx-remaining-bits ctx))))
                      (when (and (> rebalance (ash 3 +celt-bitres+)) (/= itheta 16384))
                        (incf mbits (- rebalance (ash 3 +celt-bitres+))))
                      (setf cm (logior cm (quant-partition ctx x xoff n2 mbits bb2 lowband lboff lm2 (* gain mid) fill)))))))))
        ;; no-split base case
        (let* ((q (bits2pulses i lm b)) (curr-bits (pulses2bits i lm q)))
          (decf (bctx-remaining-bits ctx) curr-bits)
          (loop while (and (< (bctx-remaining-bits ctx) 0) (> q 0)) do
            (incf (bctx-remaining-bits ctx) curr-bits)
            (decf q)
            (setf curr-bits (pulses2bits i lm q))
            (decf (bctx-remaining-bits ctx) curr-bits))
          (if (/= q 0)
              (setf cm (alg-unquant x xoff n (get-pulses q) spread bb dec gain))
              (let ((cm-mask (1- (ash 1 bb))))
                (setf fill (logand fill cm-mask))
                (if (= fill 0)
                    (dotimes (j n) (setf (aref x (+ xoff j)) 0d0))
                    (if (null lowband)
                        (progn
                          (dotimes (j n)
                            (setf (bctx-seed ctx) (celt-lcg-rand (bctx-seed ctx)))
                            (setf (aref x (+ xoff j)) (float (ash (logand-to-signed (bctx-seed ctx)) -20) 1d0)))
                          (setf cm cm-mask)
                          (renormalise-vector x xoff n gain))
                        (progn
                          (dotimes (j n)
                            (setf (bctx-seed ctx) (celt-lcg-rand (bctx-seed ctx)))
                            (let ((tmp (if (/= (logand (bctx-seed ctx) #x8000) 0) (/ 1d0 256) (/ -1d0 256))))
                              (setf (aref x (+ xoff j)) (+ (aref lowband (+ lboff j)) tmp))))
                          (setf cm fill)
                          (renormalise-vector x xoff n gain))))))))
    cm))

(declaim (inline logand-to-signed))
(defun logand-to-signed (u)
  "Interpret low 32 bits of U as a signed 32-bit int (C (opus_int32)seed)."
  (if (>= u #x80000000) (- u #x100000000) u))

(defun quant-band (ctx x xoff n b bb lowband lboff lm lbo lbooff gain lbscratch lbsoff fill)
  (declare (type f64vec x))
  (let* ((n0 n) (n-b n) (b0 bb) (time-divide 0) (recombine 0)
         (longblocks (= b0 1)) (cm 0) (dec (bctx-dec ctx)) (tf (bctx-tf-change ctx))
         (bcur bb))
    (declare (ignore dec))
    (setf n-b (floor n-b bcur))
    (when (= n 1) (return-from quant-band (quant-band-n1 ctx x xoff nil 0 lbo lbooff)))
    (when (> tf 0) (setf recombine tf))
    (when (and lbscratch lowband (or (/= recombine 0) (and (= (logand n-b 1) 0) (< tf 0)) (> b0 1)))
      (dotimes (j n) (setf (aref lbscratch (+ lbsoff j)) (aref lowband (+ lboff j))))
      (setf lowband lbscratch lboff lbsoff))
    (dotimes (k recombine)
      (when lowband (haar1 lowband lboff (ash n (- k)) (ash 1 k)))
      (setf fill (logior (aref +bit-interleave-table+ (logand fill #xf))
                         (ash (aref +bit-interleave-table+ (ash fill -4)) 2))))
    (setf bcur (ash bcur (- recombine)))
    (setf n-b (ash n-b recombine))
    (loop while (and (= (logand n-b 1) 0) (< tf 0)) do
      (when lowband (haar1 lowband lboff n-b bcur))
      (setf fill (logior fill (ash fill bcur)))
      (setf bcur (ash bcur 1) n-b (ash n-b -1))
      (incf time-divide) (incf tf))
    (setf b0 bcur)
    (let ((n-b0 n-b))
      (when (> b0 1)
        (when lowband (deinterleave-hadamard lowband lboff (ash n-b (- recombine)) (ash b0 recombine) longblocks)))
      (setf cm (quant-partition ctx x xoff n b bcur lowband lboff lm gain fill))
      ;; resynth undo
      (when (> b0 1) (interleave-hadamard x xoff (ash n-b (- recombine)) (ash b0 recombine) longblocks))
      (setf n-b n-b0)
      (let ((bb2 b0))
        (dotimes (k time-divide)
          (setf bb2 (ash bb2 -1) n-b (ash n-b 1))
          (setf cm (logior cm (ash cm (- bb2))))
          (haar1 x xoff n-b bb2))
        (dotimes (k recombine)
          (setf cm (aref +bit-deinterleave-table+ cm))
          (haar1 x xoff (ash n0 (- k)) (ash 1 k)))
        (setf bb2 (ash bb2 recombine))
        (when lbo
          (let ((nn (sqrt (float n0 1d0))))
            (dotimes (j n0) (setf (aref lbo (+ lbooff j)) (* nn (aref x (+ xoff j)))))))
        (setf cm (logand cm (1- (ash 1 bb2))))))
    cm))

(defun quant-band-stereo (ctx x xoff y yoff n b bb lowband lboff lm lbo lbooff lbscratch lbsoff fill)
  (declare (type f64vec x y))
  (let ((dec (bctx-dec ctx)) (orig-fill fill) (cm 0))
    (when (= n 1) (return-from quant-band-stereo (quant-band-n1 ctx x xoff y yoff lbo lbooff)))
    (multiple-value-bind (nb inv imid iside delta itheta qalloc nfill)
        (compute-theta ctx x xoff y yoff n b bb bb lm t fill)
      (setf b nb fill nfill)
      (let ((mid (* (/ 1d0 32768) imid)) (side (* (/ 1d0 32768) iside)))
        (if (= n 2)
            (let ((mbits b) (sbits 0) (c 0) x2 x2o y2 y2o (sign 0))
              (when (and (/= itheta 0) (/= itheta 16384)) (setf sbits (ash 1 +celt-bitres+)))
              (decf mbits sbits)
              (setf c (if (> itheta 8192) 1 0))
              (decf (bctx-remaining-bits ctx) (+ qalloc sbits))
              (if (= c 1) (setf x2 y x2o yoff y2 x y2o xoff) (setf x2 x x2o xoff y2 y y2o yoff))
              (when (/= sbits 0) (setf sign (ec-dec-bits dec 1)))
              (setf sign (- 1 (* 2 sign)))
              (setf cm (quant-band ctx x2 x2o n mbits bb lowband lboff lm lbo lbooff 1d0 lbscratch lbsoff orig-fill))
              (setf (aref y2 y2o) (* (- sign) (aref x2 (1+ x2o)))
                    (aref y2 (1+ y2o)) (* sign (aref x2 x2o)))
              ;; resynth N=2 mid/side -> L/R
              (setf (aref x xoff) (* mid (aref x xoff)) (aref x (1+ xoff)) (* mid (aref x (1+ xoff)))
                    (aref y yoff) (* side (aref y yoff)) (aref y (1+ yoff)) (* side (aref y (1+ yoff))))
              (let ((tmp (aref x xoff)))
                (setf (aref x xoff) (- tmp (aref y yoff)) (aref y yoff) (+ tmp (aref y yoff))))
              (let ((tmp (aref x (1+ xoff))))
                (setf (aref x (1+ xoff)) (- tmp (aref y (1+ yoff))) (aref y (1+ yoff)) (+ tmp (aref y (1+ yoff))))))
            (let ((mbits (max 0 (min b (floor (- b delta) 2)))) (sbits 0) (rebalance 0))
              (setf sbits (- b mbits))
              (decf (bctx-remaining-bits ctx) qalloc)
              (setf rebalance (bctx-remaining-bits ctx))
              (if (>= mbits sbits)
                  (progn
                    (setf cm (quant-band ctx x xoff n mbits bb lowband lboff lm lbo lbooff 1d0 lbscratch lbsoff fill))
                    (setf rebalance (- mbits (- rebalance (bctx-remaining-bits ctx))))
                    (when (and (> rebalance (ash 3 +celt-bitres+)) (/= itheta 0))
                      (incf sbits (- rebalance (ash 3 +celt-bitres+))))
                    (setf cm (logior cm (quant-band ctx y yoff n sbits bb nil 0 lm nil 0 side nil 0 (ash fill (- bb))))))
                  (progn
                    (setf cm (quant-band ctx y yoff n sbits bb nil 0 lm nil 0 side nil 0 (ash fill (- bb))))
                    (setf rebalance (- sbits (- rebalance (bctx-remaining-bits ctx))))
                    (when (and (> rebalance (ash 3 +celt-bitres+)) (/= itheta 16384))
                      (incf mbits (- rebalance (ash 3 +celt-bitres+))))
                    (setf cm (logior cm (quant-band ctx x xoff n mbits bb lowband lboff lm lbo lbooff 1d0 lbscratch lbsoff fill)))))))
        ;; resynth (applies to BOTH the N=2 and normal branches, as in libopus)
        (when (/= n 2) (stereo-merge x xoff y yoff mid n))
        (when (/= inv 0) (dotimes (j n) (setf (aref y (+ yoff j)) (- (aref y (+ yoff j))))))))
    cm))

;;; ==== rate.c: bit allocation ============================================
(defun %interp-bits2pulses (start end skip-start bits1 bits2 thresh cap total
                            skip-rsv intensity-rsv dual-stereo-rsv
                            pulses ebits fine-priority c lm dec)
  "Decoder interp_bits2pulses. Returns (values codedBands intensity dual-stereo balance)."
  (let* ((alloc-floor (ash c +celt-bitres+)) (stereo (if (> c 1) 1 0))
         (logm (ash lm +celt-bitres+)) (lo 0) (hi (ash 1 6)) (psum 0) (done 0)
         (codedbands 0) (left 0) (percoeff 0) (balance 0) (intensity 0) (dual-stereo 0))
    (dotimes (i 6)
      (let ((mid (ash (+ lo hi) -1)))
        (setf psum 0 done 0)
        (loop for j from (1- end) downto start do
          (let ((tmp (+ (aref bits1 j) (ash (* mid (aref bits2 j)) (- 6)))))
            (if (or (>= tmp (aref thresh j)) (= done 1))
                (progn (setf done 1) (incf psum (min tmp (aref cap j))))
                (when (>= tmp alloc-floor) (incf psum alloc-floor)))))
        (if (> psum total) (setf hi mid) (setf lo mid))))
    (setf psum 0 done 0)
    (loop for j from (1- end) downto start do
      (let ((tmp (+ (aref bits1 j) (ash (* lo (aref bits2 j)) (- 6)))))
        (if (and (< tmp (aref thresh j)) (= done 0))
            (setf tmp (if (>= tmp alloc-floor) alloc-floor 0))
            (setf done 1))
        (setf tmp (min tmp (aref cap j)))
        (setf (aref pulses j) tmp)
        (incf psum tmp)))
    (setf codedbands end)
    (loop named skiploop do
      (let* ((j (1- codedbands)) (band-width 0) (band-bits 0) (rem 0))
        (when (<= j skip-start) (incf total skip-rsv) (return-from skiploop))
        (setf left (- total psum))
        (setf percoeff (floor left (- (aref +celt-ebands+ codedbands) (aref +celt-ebands+ start))))
        (decf left (* (- (aref +celt-ebands+ codedbands) (aref +celt-ebands+ start)) percoeff))
        (setf rem (max (- left (- (aref +celt-ebands+ j) (aref +celt-ebands+ start))) 0))
        (setf band-width (- (aref +celt-ebands+ codedbands) (aref +celt-ebands+ j)))
        (setf band-bits (+ (aref pulses j) (* percoeff band-width) rem))
        (when (>= band-bits (max (aref thresh j) (+ alloc-floor (ash 1 +celt-bitres+))))
          (if (/= (ec-dec-bit-logp dec 1) 0)
              (return-from skiploop)
              (progn (incf psum (ash 1 +celt-bitres+)) (decf band-bits (ash 1 +celt-bitres+)))))
        (decf psum (+ (aref pulses j) intensity-rsv))
        (when (> intensity-rsv 0) (setf intensity-rsv (aref +celt-log2-frac-table+ (- j start))))
        (incf psum intensity-rsv)
        (if (>= band-bits alloc-floor)
            (progn (incf psum alloc-floor) (setf (aref pulses j) alloc-floor))
            (setf (aref pulses j) 0))
        (decf codedbands)))
    (when (> intensity-rsv 0)
      (setf intensity (+ start (ec-dec-uint dec (- (+ codedbands 1) start)))))
    (when (<= intensity start) (incf total dual-stereo-rsv) (setf dual-stereo-rsv 0))
    (when (> dual-stereo-rsv 0) (setf dual-stereo (ec-dec-bit-logp dec 1)))
    (setf left (- total psum))
    (setf percoeff (floor left (- (aref +celt-ebands+ codedbands) (aref +celt-ebands+ start))))
    (decf left (* (- (aref +celt-ebands+ codedbands) (aref +celt-ebands+ start)) percoeff))
    (loop for j from start below codedbands do
      (incf (aref pulses j) (* percoeff (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)))))
    (loop for j from start below codedbands do
      (let ((tmp (min left (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)))))
        (incf (aref pulses j) tmp) (decf left tmp)))
    (setf balance 0)
    (loop for j from start below codedbands do
      (let* ((n0 (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)))
             (n (ash n0 lm)) (bit (+ (aref pulses j) balance)) (excess 0) (den 0) (nclogn 0) (offset 0))
        (if (> n 1)
            (progn
              (setf excess (max (- bit (aref cap j)) 0))
              (setf (aref pulses j) (- bit excess))
              (setf den (+ (* c n) (if (and (= c 2) (> n 2) (= dual-stereo 0) (< j intensity)) 1 0)))
              (setf nclogn (* den (+ (%logn j) logm)))
              (setf offset (- (ash nclogn -1) (* den +celt-fine-offset+)))
              (when (= n 2) (incf offset (ash (ash den +celt-bitres+) -2)))
              (cond ((< (+ (aref pulses j) offset) (ash (* den 2) +celt-bitres+)) (incf offset (ash nclogn -2)))
                    ((< (+ (aref pulses j) offset) (ash (* den 3) +celt-bitres+)) (incf offset (ash nclogn -3))))
              (setf (aref ebits j) (max 0 (+ (aref pulses j) offset (ash den (1- +celt-bitres+)))))
              (setf (aref ebits j) (ash (floor (aref ebits j) den) (- +celt-bitres+)))
              (when (> (* c (aref ebits j)) (ash (aref pulses j) (- +celt-bitres+)))
                (setf (aref ebits j) (ash (ash (aref pulses j) (- stereo)) (- +celt-bitres+))))
              (setf (aref ebits j) (min (aref ebits j) +celt-max-fine-bits+))
              (setf (aref fine-priority j) (if (>= (* (aref ebits j) (ash den +celt-bitres+)) (+ (aref pulses j) offset)) 1 0))
              (decf (aref pulses j) (ash (* c (aref ebits j)) +celt-bitres+)))
            (progn
              (setf excess (max 0 (- bit (ash c +celt-bitres+))))
              (setf (aref pulses j) (- bit excess))
              (setf (aref ebits j) 0 (aref fine-priority j) 1)))
        (when (> excess 0)
          (let* ((extra-fine (min (ash excess (- (+ stereo +celt-bitres+))) (- +celt-max-fine-bits+ (aref ebits j))))
                 (extra-bits (ash (* extra-fine c) +celt-bitres+)))
            (incf (aref ebits j) extra-fine)
            (setf (aref fine-priority j) (if (>= extra-bits (- excess balance)) 1 0))
            (decf excess extra-bits)))
        (setf balance excess)))
    (loop for j from codedbands below end do
      (setf (aref ebits j) (ash (ash (aref pulses j) (- stereo)) (- +celt-bitres+)))
      (setf (aref pulses j) 0 (aref fine-priority j) (if (< (aref ebits j) 1) 1 0)))
    (values codedbands intensity dual-stereo balance)))

(defun clt-compute-allocation (start end offsets cap alloc-trim total-in pulses ebits fine-priority c lm dec)
  (let* ((nb +celt-nbebands+) (total (max total-in 0)) (skip-start start)
         (skip-rsv (if (>= total (ash 1 +celt-bitres+)) (ash 1 +celt-bitres+) 0))
         (intensity-rsv 0) (dual-stereo-rsv 0)
         (bits1 (make-array nb :initial-element 0)) (bits2 (make-array nb :initial-element 0))
         (thresh (make-array nb :initial-element 0)) (trim-offset (make-array nb :initial-element 0)))
    (decf total skip-rsv)
    (when (= c 2)
      (setf intensity-rsv (aref +celt-log2-frac-table+ (- end start)))
      (if (> intensity-rsv total) (setf intensity-rsv 0)
          (progn (decf total intensity-rsv)
                 (setf dual-stereo-rsv (if (>= total (ash 1 +celt-bitres+)) (ash 1 +celt-bitres+) 0))
                 (decf total dual-stereo-rsv))))
    (loop for j from start below end do
      (setf (aref thresh j) (max (ash c +celt-bitres+)
                                 (ash (* 3 (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)) (ash 1 lm)) (- +celt-bitres+ 4))))
      (setf (aref trim-offset j)
            (ash (* c (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)) (- alloc-trim 5 lm) (- end j 1))
                 (- (+ lm +celt-bitres+) 6)))
      (when (= (ash (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)) lm) 1)
        (decf (aref trim-offset j) (ash c +celt-bitres+))))
    (let ((lo 1) (hi (1- +celt-nballocvectors+)))
      (loop
        (let ((done 0) (psum 0) (mid (ash (+ lo hi) -1)))
          (loop for j from (1- end) downto start do
            (let* ((nn (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)))
                   (bitsj (ash (* c nn (aref +celt-alloc-vectors+ (+ (* mid nb) j))) (- lm 2))))
              (when (> bitsj 0) (setf bitsj (max 0 (+ bitsj (aref trim-offset j)))))
              (incf bitsj (aref offsets j))
              (if (or (>= bitsj (aref thresh j)) (= done 1))
                  (progn (setf done 1) (incf psum (min bitsj (aref cap j))))
                  (when (>= bitsj (ash c +celt-bitres+)) (incf psum (ash c +celt-bitres+))))))
          (if (> psum total) (setf hi (1- mid)) (setf lo (1+ mid))))
        (when (> lo hi) (return)))
      (setf hi lo) (decf lo)
      (loop for j from start below end do
        (let* ((nn (- (aref +celt-ebands+ (1+ j)) (aref +celt-ebands+ j)))
               (b1 (ash (* c nn (aref +celt-alloc-vectors+ (+ (* lo nb) j))) (- lm 2)))
               (b2 (if (>= hi +celt-nballocvectors+) (aref cap j)
                       (ash (* c nn (aref +celt-alloc-vectors+ (+ (* hi nb) j))) (- lm 2)))))
          (when (> b1 0) (setf b1 (max 0 (+ b1 (aref trim-offset j)))))
          (when (> b2 0) (setf b2 (max 0 (+ b2 (aref trim-offset j)))))
          (when (> lo 0) (incf b1 (aref offsets j)))
          (incf b2 (aref offsets j))
          (when (> (aref offsets j) 0) (setf skip-start j))
          (setf b2 (max 0 (- b2 b1)))
          (setf (aref bits1 j) b1 (aref bits2 j) b2))))
    (%interp-bits2pulses start end skip-start bits1 bits2 thresh cap total
                         skip-rsv intensity-rsv dual-stereo-rsv pulses ebits fine-priority c lm dec)))

(defun init-caps (cap lm c)
  (dotimes (i +celt-nbebands+)
    (let ((n (ash (- (aref +celt-ebands+ (1+ i)) (aref +celt-ebands+ i)) lm)))
      (setf (aref cap i)
            (ash (* (+ (aref +celt-cache-caps+ (+ (* +celt-nbebands+ (+ (* 2 lm) c -1)) i)) 64) c n) -2)))))

;;; ==== quant_all_bands (bands.c) =========================================
(defparameter *opus-rfc8251* nil
  "When true, decode with the RFC 8251 decoder update (a.k.a. the libopus
`UPDATE_DRAFT` behaviour: special_hybrid_folding + the extended lowband/fold
range in hybrid bands), matching a default libopus 1.4 decode.  When nil (the
default) reed decodes to the *original* RFC 6716 semantics, which is what the
official RFC 6716 test vectors (testvector*.dec) were produced with.  The two
differ only in the hybrid (SILK+CELT) crossover bands.")

(defun special-hybrid-folding (norm norm2off start m dual-stereo)
  "bands.c special_hybrid_folding: when start != 0 (hybrid), duplicate enough of
the first coded band's normalised folding data so the (wider) second band can
fold across its full width.  A no-op for CELT-only (start = 0 is never called)."
  (declare (type f64vec norm))
  (let* ((eb +celt-ebands+)
         (n1 (* m (- (aref eb (+ start 1)) (aref eb start))))
         (n2 (* m (- (aref eb (+ start 2)) (aref eb (+ start 1))))))
    (replace norm norm :start1 n1 :end1 n2 :start2 (- (* 2 n1) n2))
    (when (/= dual-stereo 0)
      (replace norm norm :start1 (+ norm2off n1) :end1 (+ norm2off n2)
                         :start2 (+ norm2off (- (* 2 n1) n2))))))

(defun quant-all-bands (start end x y collapse-masks pulses shortblocks spread
                        dual-stereo intensity tf-res total-bits balance dec lm codedbands seed)
  "Decode all bands into X (mono) or X/Y (stereo, Y=X offset N)."
  (declare (type f64vec x))
  (let* ((nb +celt-nbebands+) (m (ash 1 lm)) (bcur (if (/= shortblocks 0) m 1))
         (norm-offset (* m (aref +celt-ebands+ start)))
         (norm-len (- (* m (aref +celt-ebands+ (1- nb))) norm-offset))
         (norm (mkf64 (* 2 norm-len))) (norm2off norm-len)
         (nn (* m +celt-shortmdctsize+))
         (cc (if y 2 1)) (lowband-offset 0) (update-lowband t)
         (lbscratch-off (* m (aref +celt-ebands+ (1- nb))))
         (ctx (make-bctx :dec dec :intensity intensity :spread spread :seed seed)))
    (loop for i from start below end do
      (let* ((last (= i (1- end))) (xoff (* m (aref +celt-ebands+ i)))
             (yoff (+ nn (* m (aref +celt-ebands+ i))))
             (n (- (* m (aref +celt-ebands+ (1+ i))) (* m (aref +celt-ebands+ i))))
             (tell (ec-tell-frac dec)) (b 0) (rembits 0)
             (eff-lowband -1) (x-cm 0) (y-cm 0) (tf-change (aref tf-res i)))
        (setf (bctx-i ctx) i (bctx-tf-change ctx) tf-change)
        (when (/= i start) (decf balance tell))
        (setf rembits (- total-bits tell 1))
        (setf (bctx-remaining-bits ctx) rembits)
        (if (<= i (1- codedbands))
            (let ((curr-balance (truncate balance (min 3 (- codedbands i)))))
              (setf b (max 0 (min 16383 (min (1+ rembits) (+ (aref pulses i) curr-balance))))))
            (setf b 0))
        (when (and (or (>= (- (* m (aref +celt-ebands+ i)) n) (* m (aref +celt-ebands+ start)))
                       (and *opus-rfc8251* (= i (1+ start))))
                   (or update-lowband (= lowband-offset 0)))
          (setf lowband-offset i))
        (when (and *opus-rfc8251* (= i (1+ start)))
          (special-hybrid-folding norm norm2off start m dual-stereo))
        (let ((lbscratch-avail (not last)))
          (if (and (/= lowband-offset 0) (or (/= spread 3) (> bcur 1) (< tf-change 0)))
              (let ((fold-start 0) (fold-end 0))
                (setf eff-lowband (max 0 (- (* m (aref +celt-ebands+ lowband-offset)) norm-offset n)))
                (setf fold-start lowband-offset)
                (loop (decf fold-start) (when (<= (* m (aref +celt-ebands+ fold-start)) (+ eff-lowband norm-offset)) (return)))
                (setf fold-end (1- lowband-offset))
                (loop (incf fold-end) (when (or (and *opus-rfc8251* (>= fold-end i)) (>= (* m (aref +celt-ebands+ fold-end)) (+ eff-lowband norm-offset n))) (return)))
                (setf x-cm 0 y-cm 0)
                (loop for fi from fold-start below fold-end do
                  (setf x-cm (logior x-cm (aref collapse-masks (+ (* fi cc) 0))))
                  (setf y-cm (logior y-cm (aref collapse-masks (+ (* fi cc) (1- cc)))))))
              (setf x-cm (1- (ash 1 bcur)) y-cm (1- (ash 1 bcur))))
          (when (and (/= dual-stereo 0) (= i intensity))
            (setf dual-stereo 0)
            (dotimes (j (- (* m (aref +celt-ebands+ i)) norm-offset))
              (setf (aref norm j) (* 0.5d0 (+ (aref norm j) (aref norm (+ norm2off j)))))))
          (let ((lout-off (- (* m (aref +celt-ebands+ i)) norm-offset)))
            (if (/= dual-stereo 0)
                (progn
                  (setf x-cm (quant-band ctx x xoff n (ash b -1) bcur
                                         (if (/= eff-lowband -1) norm nil) (if (/= eff-lowband -1) eff-lowband 0)
                                         lm (if last nil norm) lout-off 1d0
                                         (if lbscratch-avail x nil) lbscratch-off x-cm))
                  (setf y-cm (quant-band ctx x yoff n (ash b -1) bcur
                                         (if (/= eff-lowband -1) norm nil) (if (/= eff-lowband -1) (+ norm2off eff-lowband) 0)
                                         lm (if last nil norm) (+ norm2off lout-off) 1d0
                                         (if lbscratch-avail x nil) lbscratch-off y-cm)))
                (progn
                  (if y
                      (setf x-cm (quant-band-stereo ctx x xoff x yoff n b bcur
                                                    (if (/= eff-lowband -1) norm nil) (if (/= eff-lowband -1) eff-lowband 0)
                                                    lm (if last nil norm) lout-off
                                                    (if lbscratch-avail x nil) lbscratch-off (logior x-cm y-cm)))
                      (setf x-cm (quant-band ctx x xoff n b bcur
                                             (if (/= eff-lowband -1) norm nil) (if (/= eff-lowband -1) eff-lowband 0)
                                             lm (if last nil norm) lout-off 1d0
                                             (if lbscratch-avail x nil) lbscratch-off (logior x-cm y-cm))))
                  (setf y-cm x-cm)))
            (setf (aref collapse-masks (+ (* i cc) 0)) x-cm)
            (setf (aref collapse-masks (+ (* i cc) (1- cc))) y-cm)
            (incf balance (+ (aref pulses i) tell))
            (setf update-lowband (> b (ash n +celt-bitres+)))))))
    (bctx-seed ctx)))

;;; ==== denormalise / anti-collapse (bands.c) =============================
(defun denormalise-bands (x xoff freq bandloge boff start end silence)
  (declare (type f64vec x freq))
  (let* ((m (/ (length freq) +celt-shortmdctsize+))  ; = M
         (nn (length freq)) (bound (* m (aref +celt-ebands+ end))))
    (when (/= silence 0) (setf bound 0 start 0 end 0))
    (dotimes (i (* m (aref +celt-ebands+ start))) (setf (aref freq i) 0d0))
    (loop for i from start below end do
      (let* ((jstart (* m (aref +celt-ebands+ i))) (jend (* m (aref +celt-ebands+ (1+ i))))
             (lg (+ (aref bandloge (+ boff i)) (aref +celt-emeans+ i)))
             (g (expt 2d0 (min 32d0 lg))))
        (loop for j from jstart below jend do
          (setf (aref freq j) (* (aref x (+ xoff j)) g)))))
    (loop for i from bound below nn do (setf (aref freq i) 0d0))))

(defun anti-collapse (x collapse-masks lm cc size start end loge prev1 prev2 pulses seed)
  (declare (type f64vec x))
  (let ((nb +celt-nbebands+))
    (loop for i from start below end do
      (let* ((n0 (- (aref +celt-ebands+ (1+ i)) (aref +celt-ebands+ i)))
             (depth (ash (floor (+ 1 (aref pulses i)) (- (aref +celt-ebands+ (1+ i)) (aref +celt-ebands+ i))) (- lm)))
             (thresh (* 0.5d0 (expt 2d0 (* -0.125d0 depth))))
             (sqrt-1 (/ 1d0 (sqrt (float (ash n0 lm) 1d0)))))
        (dotimes (c cc)
          (let* ((p1 (aref prev1 (+ (* c nb) i))) (p2 (aref prev2 (+ (* c nb) i))) (renorm nil))
            (when (= cc 1)
              (setf p1 (max p1 (aref prev1 (+ nb i))) p2 (max p2 (aref prev2 (+ nb i)))))
            (let* ((ediff (max 0d0 (- (aref loge (+ (* c nb) i)) (min p1 p2))))
                   (r (* 2d0 (expt 2d0 (- ediff)))))
              (when (= lm 3) (setf r (* r 1.41421356d0)))
              (setf r (min thresh r) r (* r sqrt-1))
              (let ((xo (+ (* c size) (ash (aref +celt-ebands+ i) lm))))
                (dotimes (k (ash 1 lm))
                  (when (= (logand (aref collapse-masks (+ (* i cc) c)) (ash 1 k)) 0)
                    (dotimes (j n0)
                      (setf seed (celt-lcg-rand seed))
                      (setf (aref x (+ xo (ash j lm) k)) (if (/= (logand seed #x8000) 0) r (- r))))
                    (setf renorm t)))
                (when renorm (renormalise-vector x xo (ash n0 lm) 1d0))))))))))

;;; ==== Laplace + energy decode (laplace.c / quant_bands.c) ================
(defun ec-laplace-decode (dec fs decay)
  (let ((val 0) (fl 0) (fm (ec-decode-bin dec 15)))
    (when (>= fm fs)
      (incf val) (setf fl fs)
      (setf fs (+ (ash (* (- 32768 32 fs) (- 16384 decay)) -15) 1))  ; get_freq1 + MINP
      (loop while (and (> fs 1) (>= fm (+ fl (* 2 fs)))) do
        (setf fs (* fs 2)) (incf fl fs)
        (setf fs (+ (ash (* (- fs 2) decay) -15) 1)) (incf val))
      (when (<= fs 1)
        (let ((di (ash (- fm fl) -1)))
          (incf val di) (incf fl (* 2 di))))
      (if (< fm (+ fl fs)) (setf val (- val)) (incf fl fs)))
    (ec-dec-update dec fl (min (+ fl fs) 32768) 32768)
    val))

(defun unquant-coarse-energy (start end oldbande intra dec c lm)
  (let* ((nb +celt-nbebands+) (pm (aref (aref +celt-e-prob-model+ lm) intra))
         (prev (make-array 2 :element-type 'double-float :initial-element 0d0))
         (coef (if (/= intra 0) 0d0 (aref +celt-pred-coef+ lm)))
         (beta (if (/= intra 0) +celt-beta-intra+ (aref +celt-beta-coef+ lm)))
         (budget (* (ec-dec-storage dec) 8)))
    (loop for i from start below end do
      (dotimes (cc c)
        (let ((tell (ec-tell dec)) (qi 0))
          (cond
            ((>= (- budget tell) 15)
             (let ((pidx (* 2 (min i 20))))
               (setf qi (ec-laplace-decode dec (ash (aref pm pidx) 7) (ash (aref pm (1+ pidx)) 6)))))
            ((>= (- budget tell) 2)
             (let ((q (ec-dec-icdf dec +celt-small-energy-icdf+ 2)))
               (setf qi (logxor (ash q -1) (- (logand q 1))))))
            ((>= (- budget tell) 1) (setf qi (- (ec-dec-bit-logp dec 1))))
            (t (setf qi -1)))
          (let* ((q (float qi 1d0))
                 (olde (max -9d0 (aref oldbande (+ i (* cc nb)))))
                 (tmp (+ (* coef olde) (aref prev cc) q)))
            (setf (aref oldbande (+ i (* cc nb))) tmp)
            (setf (aref prev cc) (+ (aref prev cc) q (- (* beta q))))))))))

(defun unquant-fine-energy (start end oldbande fine-quant dec c)
  (let ((nb +celt-nbebands+))
    (loop for i from start below end do
      (when (> (aref fine-quant i) 0)
        (dotimes (cc c)
          (let* ((q2 (ec-dec-bits dec (aref fine-quant i)))
                 (offset (- (* (+ q2 0.5d0) (ash 1 (- 14 (aref fine-quant i))) (/ 1d0 16384)) 0.5d0)))
            (incf (aref oldbande (+ i (* cc nb))) offset)))))))

(defun unquant-energy-finalise (start end oldbande fine-quant fine-priority bits-left dec c)
  (let ((nb +celt-nbebands+))
    (dotimes (prio 2)
      (loop for i from start below end while (>= bits-left c) do
        (when (and (< (aref fine-quant i) +celt-max-fine-bits+) (= (aref fine-priority i) prio))
          (dotimes (cc c)
            (let* ((q2 (ec-dec-bits dec 1))
                   (offset (* (- q2 0.5d0) (ash 1 (- 14 (aref fine-quant i) 1)) (/ 1d0 16384))))
              (incf (aref oldbande (+ i (* cc nb))) offset)
              (decf bits-left))))))))

;;; ==== tf_decode (celt_decoder.c) ========================================
(defun tf-decode (start end is-transient tf-res lm dec)
  (let* ((budget (* (ec-dec-storage dec) 8)) (tell (ec-tell dec))
         (logp (if (/= is-transient 0) 2 4))
         (tf-select-rsv (if (and (> lm 0) (<= (+ tell logp 1) budget)) 1 0))
         (tf-changed 0) (curr 0) (tf-select 0))
    (decf budget tf-select-rsv)
    (loop for i from start below end do
      (when (<= (+ tell logp) budget)
        (setf curr (logxor curr (ec-dec-bit-logp dec logp)))
        (setf tell (ec-tell dec))
        (setf tf-changed (logior tf-changed curr)))
      (setf (aref tf-res i) curr)
      (setf logp (if (/= is-transient 0) 4 5)))
    (let ((tbl (aref +celt-tf-select-table+ lm)))
      (when (and (/= tf-select-rsv 0)
                 (/= (aref tbl (+ (* 4 is-transient) 0 tf-changed))
                     (aref tbl (+ (* 4 is-transient) 2 tf-changed))))
        (setf tf-select (ec-dec-bit-logp dec 1)))
      (loop for i from start below end do
        (setf (aref tf-res i) (aref tbl (+ (* 4 is-transient) (* 2 tf-select) (aref tf-res i))))))))

;;; ==== comb filter (post-filter) + deemphasis (celt.c / celt_decoder.c) ==
(defun comb-filter (arr off t0 t1 n g0 g1 tapset0 tapset1 window overlap)
  (declare (type f64vec arr window))
  (when (and (= g0 0d0) (= g1 0d0)) (return-from comb-filter))
  (setf t0 (max t0 +combfilter-minperiod+) t1 (max t1 +combfilter-minperiod+))
  (let* ((gt0 (aref +celt-comb-gains+ tapset0)) (gt1 (aref +celt-comb-gains+ tapset1))
         (g00 (* g0 (aref gt0 0))) (g01 (* g0 (aref gt0 1))) (g02 (* g0 (aref gt0 2)))
         (g10 (* g1 (aref gt1 0))) (g11 (* g1 (aref gt1 1))) (g12 (* g1 (aref gt1 2)))
         (x1 (aref arr (+ off (- t1) 1))) (x2 (aref arr (+ off (- t1))))
         (x3 (aref arr (+ off (- t1) -1))) (x4 (aref arr (+ off (- t1) -2))))
    (when (and (= g0 g1) (= t0 t1) (= tapset0 tapset1)) (setf overlap 0))
    (dotimes (i overlap)
      (let* ((x0 (aref arr (+ off i (- t1) 2))) (f (* (aref window i) (aref window i))))
        (setf (aref arr (+ off i))
              (+ (aref arr (+ off i))
                 (* (- 1d0 f) g00 (aref arr (+ off i (- t0))))
                 (* (- 1d0 f) g01 (+ (aref arr (+ off i (- t0) 1)) (aref arr (+ off i (- t0) -1))))
                 (* (- 1d0 f) g02 (+ (aref arr (+ off i (- t0) 2)) (aref arr (+ off i (- t0) -2))))
                 (* f g10 x2) (* f g11 (+ x1 x3)) (* f g12 (+ x0 x4))))
        (setf x4 x3 x3 x2 x2 x1 x1 x0)))
    (when (= g1 0d0) (return-from comb-filter))
    (let ((i overlap))
      (setf x4 (aref arr (+ off i (- t1) -2)) x3 (aref arr (+ off i (- t1) -1))
            x2 (aref arr (+ off i (- t1))) x1 (aref arr (+ off i (- t1) 1)))
      (loop for idx from i below n do
        (let ((x0 (aref arr (+ off idx (- t1) 2))))
          (setf (aref arr (+ off idx))
                (+ (aref arr (+ off idx)) (* g10 x2) (* g11 (+ x1 x3)) (* g12 (+ x0 x4))))
          (setf x4 x3 x3 x2 x2 x1 x1 x0))))))

;;; ==== decoder state + top-level CELT frame decode =======================
(defstruct (celt-decoder (:constructor %make-celt-decoder))
  (channels 1 :type fixnum) (stream-channels 1 :type fixnum)
  (start 0 :type fixnum) (end 21 :type fixnum) (downsample 1 :type fixnum)
  decode-mem old-bande old-loge old-loge2 background-loge preemph-memd
  (postfilter-period 0 :type fixnum) (postfilter-period-old 0 :type fixnum)
  (postfilter-gain 0d0 :type double-float) (postfilter-gain-old 0d0 :type double-float)
  (postfilter-tapset 0 :type fixnum) (postfilter-tapset-old 0 :type fixnum)
  (rng 0 :type (unsigned-byte 32)) (loss-duration 0 :type fixnum))

(defun make-celt-decoder (channels)
  (let ((nb +celt-nbebands+) (dmsz (+ +celt-decode-buffer-size+ +celt-overlap+)))
    (%make-celt-decoder
     :channels channels :stream-channels channels :start 0 :end nb
     :decode-mem (let ((v (make-array channels)))
                   (dotimes (c channels) (setf (aref v c) (mkf64 dmsz))) v)
     :old-bande (mkf64 (* 2 nb)) :old-loge (mkf64 (* 2 nb))
     :old-loge2 (mkf64 (* 2 nb)) :background-loge (mkf64 (* 2 nb))
     :preemph-memd (mkf64 channels))))

(defun %celt-synthesis (st x oldbande lm is-transient silence)
  "Denormalise X and inverse-MDCT into each channel's decode-mem out_syn region."
  (declare (type f64vec x oldbande))
  (let* ((cc (celt-decoder-channels st)) (c (celt-decoder-stream-channels st))
         (nb +celt-nbebands+) (m (ash 1 lm)) (n (* m +celt-shortmdctsize+))
         (effend (min (celt-decoder-end st) +celt-effebands+))
         (start (celt-decoder-start st))
         (b (if (/= is-transient 0) m 1)) (nbb (if (/= is-transient 0) +celt-shortmdctsize+ n))
         (shift (if (/= is-transient 0) +celt-maxlm+ (- +celt-maxlm+ lm)))
         (dm (celt-decoder-decode-mem st)) (win +celt-window+)
         (osoff (- +celt-decode-buffer-size+ n))
         (freq (mkf64 n)))
    (flet ((mdct-into (chan freq-src)
             (dotimes (bb b)
               (clt-mdct-backward freq-src bb (aref dm chan) (+ osoff (* nbb bb))
                                  +celt-mdct-n+ +celt-overlap+ shift b win))))
      (cond
        ((and (= cc 2) (= c 1))                  ; mono stream -> stereo out (duplicate)
         (denormalise-bands x 0 freq oldbande 0 start effend silence)
         (mdct-into 0 freq) (mdct-into 1 freq))
        ((and (= cc 1) (= c 2))                  ; stereo stream -> mono out (downmix)
         (let ((freq2 (mkf64 n)))
           (denormalise-bands x 0 freq oldbande 0 start effend silence)
           (denormalise-bands x n freq2 oldbande nb start effend silence)
           (dotimes (i n) (setf (aref freq i) (* 0.5d0 (+ (aref freq i) (aref freq2 i)))))
           (mdct-into 0 freq)))
        (t                                        ; normal mono or stereo
         (dotimes (ch cc)
           (denormalise-bands x (* ch n) freq oldbande (* ch nb) start effend silence)
           (mdct-into ch freq)))))))

(defun %celt-deemphasis (st n pcm-out)
  "De-emphasis of each channel's out_syn into interleaved float pcm [-1,1]."
  (declare (type f64vec pcm-out))
  (let* ((cc (celt-decoder-channels st)) (dm (celt-decoder-decode-mem st))
         (mem (celt-decoder-preemph-memd st)) (coef0 +celt-preemph0+)
         (osoff (- +celt-decode-buffer-size+ n)))
    (declare (type f64vec mem))
    (dotimes (c cc)
      (let ((m (aref mem c)) (buf (aref dm c)))
        (declare (type f64vec buf))
        (dotimes (j n)
          (let ((tmp (+ (aref buf (+ osoff j)) 1d-30 m)))
            (setf m (* coef0 tmp))
            (setf (aref pcm-out (+ (* j cc) c)) (* tmp (/ 1d0 32768)))))
        (setf (aref mem c) m)))))

(defun %celt-reset (st)
  "OPUS_RESET_STATE for the CELT decoder (celt_decoder.c): clear everything from
the `rng` field on, and re-seed the log-energy history to -28 dB."
  (let ((nb +celt-nbebands+))
    (dotimes (c (celt-decoder-channels st)) (fill (aref (celt-decoder-decode-mem st) c) 0d0))
    (fill (celt-decoder-old-bande st) 0d0)
    (fill (celt-decoder-background-loge st) 0d0)
    (fill (celt-decoder-preemph-memd st) 0d0)
    (fill (celt-decoder-old-loge st) -28d0)
    (fill (celt-decoder-old-loge2 st) -28d0)
    (setf (celt-decoder-postfilter-period st) 0 (celt-decoder-postfilter-period-old st) 0
          (celt-decoder-postfilter-gain st) 0d0 (celt-decoder-postfilter-gain-old st) 0d0
          (celt-decoder-postfilter-tapset st) 0 (celt-decoder-postfilter-tapset-old st) 0
          (celt-decoder-rng st) 0 (celt-decoder-loss-duration st) 0))
  st)

(defun celt-decode-frame (st data base len lm)
  "Decode one CELT frame from DATA[base,base+len).  Returns an interleaved
double-float PCM vector of length channels*N in [-1,1] (N = 120<<lm)."
  (celt-decode-with-ec st (ec-dec-init data :base base :storage len) len lm))

(defun celt-decode-with-ec (st dec len lm)
  "Decode one CELT frame from an already-initialised range decoder DEC that
covers LEN bytes.  Shared by CELT-only decode, hybrid (where SILK has already
consumed the low-band bits from DEC) and the redundancy frames.  Returns an
interleaved double-float PCM vector of length channels*N in [-1,1]."
  (let* ((cc (celt-decoder-channels st)) (c (celt-decoder-stream-channels st))
         (nb +celt-nbebands+) (m (ash 1 lm)) (n (* m +celt-shortmdctsize+))
         (start (celt-decoder-start st)) (end (celt-decoder-end st))
         (oldbande (celt-decoder-old-bande st)) (oldloge (celt-decoder-old-loge st))
         (oldloge2 (celt-decoder-old-loge2 st)) (bgloge (celt-decoder-background-loge st))
         (total-bits (* len 8)))
    (when (= c 1)
      (dotimes (i nb) (setf (aref oldbande i) (max (aref oldbande i) (aref oldbande (+ nb i))))))
    (let ((tell (ec-tell dec)) (silence 0)
          (pf-gain 0d0) (pf-pitch 0) (pf-tapset 0) (is-transient 0) (intra-ener 0))
      (cond ((>= tell total-bits) (setf silence 1))
            ((= tell 1) (setf silence (ec-dec-bit-logp dec 15))))
      (when (/= silence 0)
        (setf tell (* len 8))
        (incf (ec-dec-nbits-total dec) (- tell (ec-tell dec))))
      (when (and (= start 0) (<= (+ tell 16) total-bits))
        (when (/= (ec-dec-bit-logp dec 1) 0)
          (let ((octave (ec-dec-uint dec 6)))
            (setf pf-pitch (- (+ (ash 16 octave) (ec-dec-bits dec (+ 4 octave))) 1))
            (let ((qg (ec-dec-bits dec 3)))
              (when (<= (+ (ec-tell dec) 2) total-bits)
                (setf pf-tapset (ec-dec-icdf dec +celt-tapset-icdf+ 2)))
              (setf pf-gain (* 0.09375d0 (+ qg 1))))))
        (setf tell (ec-tell dec)))
      (if (and (> lm 0) (<= (+ tell 3) total-bits))
          (progn (setf is-transient (ec-dec-bit-logp dec 3)) (setf tell (ec-tell dec)))
          (setf is-transient 0))
      (setf intra-ener (if (<= (+ tell 3) total-bits) (ec-dec-bit-logp dec 3) 0))
      (unquant-coarse-energy start end oldbande intra-ener dec c lm)
      (let ((tf-res (make-array nb :initial-element 0)))
        (tf-decode start end is-transient tf-res lm dec)
        (setf tell (ec-tell dec))
        (let ((spread 2))
          (when (<= (+ tell 4) total-bits) (setf spread (ec-dec-icdf dec +celt-spread-icdf+ 5)))
          (let ((cap (make-array nb :initial-element 0)) (offsets (make-array nb :initial-element 0)))
            (init-caps cap lm c)
            (let ((dynalloc-logp 6) (tot (ash total-bits +celt-bitres+)) (tellf (ec-tell-frac dec)))
              (loop for i from start below end do
                (let* ((width (ash (* c (- (aref +celt-ebands+ (1+ i)) (aref +celt-ebands+ i))) lm))
                       (quanta (min (ash width +celt-bitres+) (max (ash 6 +celt-bitres+) width)))
                       (dll dynalloc-logp) (boost 0))
                  (loop while (and (< (+ tellf (ash dll +celt-bitres+)) tot) (< boost (aref cap i))) do
                    (let ((flag (ec-dec-bit-logp dec dll)))
                      (setf tellf (ec-tell-frac dec))
                      (when (= flag 0) (return))
                      (incf boost quanta) (decf tot quanta) (setf dll 1)))
                  (setf (aref offsets i) boost)
                  (when (> boost 0) (setf dynalloc-logp (max 2 (1- dynalloc-logp))))))
              (let* ((alloc-trim (if (<= (+ tellf (ash 6 +celt-bitres+)) tot)
                                     (ec-dec-icdf dec +celt-trim-icdf+ 7) 5))
                     (bits (- (ash (* len 8) +celt-bitres+) (ec-tell-frac dec) 1))
                     (anti-collapse-rsv (if (and (/= is-transient 0) (>= lm 2)
                                                 (>= bits (ash (+ lm 2) +celt-bitres+)))
                                            (ash 1 +celt-bitres+) 0))
                     (pulses (make-array nb :initial-element 0))
                     (fine-quant (make-array nb :initial-element 0))
                     (fine-priority (make-array nb :initial-element 0)))
                (decf bits anti-collapse-rsv)
                (multiple-value-bind (codedbands intensity dual-stereo balance)
                    (clt-compute-allocation start end offsets cap alloc-trim bits
                                            pulses fine-quant fine-priority c lm dec)
                  (unquant-fine-energy start end oldbande fine-quant dec c)
                  ;; shift decode history left by N (make room for this frame)
                  (let ((cnt (+ (- +celt-decode-buffer-size+ n) (ash +celt-overlap+ -1)))
                        (dm (celt-decoder-decode-mem st)))
                    (dotimes (ch cc) (replace (aref dm ch) (aref dm ch) :start1 0 :start2 n :end2 (+ n cnt))))
                  (let* ((x (mkf64 (* c n)))
                         (collapse (make-array (* c nb) :element-type '(unsigned-byte 8) :initial-element 0)))
                    (setf (celt-decoder-rng st)
                          (quant-all-bands start end x (if (= c 2) x nil) collapse pulses
                                           is-transient spread dual-stereo intensity tf-res
                                           (- (* len (ash 8 +celt-bitres+)) anti-collapse-rsv)
                                           balance dec lm codedbands (celt-decoder-rng st)))
                    (let ((anti-collapse-on 0))
                      (when (> anti-collapse-rsv 0) (setf anti-collapse-on (ec-dec-bits dec 1)))
                      (unquant-energy-finalise start end oldbande fine-quant fine-priority
                                               (- (* len 8) (ec-tell dec)) dec c)
                      (when (/= anti-collapse-on 0)
                        (anti-collapse x collapse lm c n start end oldbande oldloge oldloge2 pulses
                                       (celt-decoder-rng st)))
                      (when (/= silence 0)
                        (dotimes (i (* c nb)) (setf (aref oldbande i) -28d0)))
                      (%celt-synthesis st x oldbande lm is-transient silence)
                      ;; post-filter (pitch comb filter)
                      (let ((dm (celt-decoder-decode-mem st)) (win +celt-window+)
                            (sm +celt-shortmdctsize+))
                        (dotimes (ch cc)
                          (let ((osoff (- +celt-decode-buffer-size+ n)))
                            (setf (celt-decoder-postfilter-period st)
                                  (max (celt-decoder-postfilter-period st) +combfilter-minperiod+)
                                  (celt-decoder-postfilter-period-old st)
                                  (max (celt-decoder-postfilter-period-old st) +combfilter-minperiod+))
                            (comb-filter (aref dm ch) osoff
                                         (celt-decoder-postfilter-period-old st)
                                         (celt-decoder-postfilter-period st) sm
                                         (celt-decoder-postfilter-gain-old st)
                                         (celt-decoder-postfilter-gain st)
                                         (celt-decoder-postfilter-tapset-old st)
                                         (celt-decoder-postfilter-tapset st) win +celt-overlap+)
                            (when (/= lm 0)
                              (comb-filter (aref dm ch) (+ osoff sm)
                                           (celt-decoder-postfilter-period st) pf-pitch (- n sm)
                                           (celt-decoder-postfilter-gain st) pf-gain
                                           (celt-decoder-postfilter-tapset st) pf-tapset win +celt-overlap+)))))
                      (setf (celt-decoder-postfilter-period-old st) (celt-decoder-postfilter-period st)
                            (celt-decoder-postfilter-gain-old st) (celt-decoder-postfilter-gain st)
                            (celt-decoder-postfilter-tapset-old st) (celt-decoder-postfilter-tapset st)
                            (celt-decoder-postfilter-period st) pf-pitch
                            (celt-decoder-postfilter-gain st) pf-gain
                            (celt-decoder-postfilter-tapset st) pf-tapset)
                      (when (/= lm 0)
                        (setf (celt-decoder-postfilter-period-old st) (celt-decoder-postfilter-period st)
                              (celt-decoder-postfilter-gain-old st) (celt-decoder-postfilter-gain st)
                              (celt-decoder-postfilter-tapset-old st) (celt-decoder-postfilter-tapset st)))
                      ;; energy state update
                      (when (= c 1) (replace oldbande oldbande :start1 nb :start2 0 :end2 nb))
                      (if (= is-transient 0)
                          (progn (replace oldloge2 oldloge :end1 (* 2 nb))
                                 (replace oldloge oldbande :end1 (* 2 nb)))
                          (dotimes (i (* 2 nb)) (setf (aref oldloge i) (min (aref oldloge i) (aref oldbande i)))))
                      (let ((mbi (* (min 160 (+ (celt-decoder-loss-duration st) m)) 0.001d0)))
                        (dotimes (i (* 2 nb))
                          (setf (aref bgloge i) (min (+ (aref bgloge i) mbi) (aref oldbande i)))))
                      (dotimes (ch 2)
                        (dotimes (i start)
                          (setf (aref oldbande (+ (* ch nb) i)) 0d0
                                (aref oldloge (+ (* ch nb) i)) -28d0 (aref oldloge2 (+ (* ch nb) i)) -28d0))
                        (loop for i from end below nb do
                          (setf (aref oldbande (+ (* ch nb) i)) 0d0
                                (aref oldloge (+ (* ch nb) i)) -28d0 (aref oldloge2 (+ (* ch nb) i)) -28d0)))
                      (setf (celt-decoder-rng st) (ec-dec-rng dec)
                            (celt-decoder-loss-duration st) 0)
                      (let ((pcm-out (mkf64 (* cc n))))
                        (%celt-deemphasis st n pcm-out)
                        pcm-out))))))))))))
