;;;; src/sideinfo.lisp — Layer III side information.
(in-package #:reed)

(defstruct (side-info (:conc-name si-))
  (main-data-begin 0 :type fixnum)
  (ngr 2 :type fixnum)
  (scfsi              (make-array '(2 4) :element-type 'fixnum :initial-element 0))
  (part2-3-length     (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (big-values         (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (global-gain        (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (scalefac-compress  (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (win-switch         (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (block-type         (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (mixed              (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (table-select       (make-array '(2 2 3) :element-type 'fixnum :initial-element 0))
  (subblock-gain      (make-array '(2 2 3) :element-type 'fixnum :initial-element 0))
  (region0-count      (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (region1-count      (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (preflag            (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (scalefac-scale     (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (count1table-select (make-array '(2 2) :element-type 'fixnum :initial-element 0))
  (count1             (make-array '(2 2) :element-type 'fixnum :initial-element 0)))

(defun parse-side-info (header br)
  "Parse the side information for HEADER from bit reader BR (positioned at the
start of the side-info bytes).  Returns a fresh SIDE-INFO."
  (declare (type bitreader br))
  (let* ((si (make-side-info))
         (nch (fh-channels header))
         (mpeg1p (eq (fh-version header) :mpeg1))
         (ngr (if mpeg1p 2 1)))
    (setf (si-ngr si) ngr)
    (setf (si-main-data-begin si) (read-bits br (if mpeg1p 9 8)))
    ;; private bits (ignored)
    (read-bits br (if mpeg1p (if (= nch 1) 5 3) (if (= nch 1) 1 2)))
    (when mpeg1p
      (dotimes (ch nch)
        (dotimes (band 4)
          (setf (aref (si-scfsi si) ch band) (read-bit br)))))
    (dotimes (gr ngr)
      (dotimes (ch nch)
        (setf (aref (si-part2-3-length si) gr ch) (read-bits br 12)
              (aref (si-big-values si) gr ch) (read-bits br 9)
              (aref (si-global-gain si) gr ch) (read-bits br 8)
              (aref (si-scalefac-compress si) gr ch) (read-bits br (if mpeg1p 4 9)))
        (let ((wsf (read-bit br)))
          (setf (aref (si-win-switch si) gr ch) wsf)
          (cond
            ((= wsf 1)
             (setf (aref (si-block-type si) gr ch) (read-bits br 2)
                   (aref (si-mixed si) gr ch) (read-bit br))
             (dotimes (r 2)
               (setf (aref (si-table-select si) gr ch r) (read-bits br 5)))
             (dotimes (w 3)
               (setf (aref (si-subblock-gain si) gr ch w) (read-bits br 3)))
             ;; implicit region counts for short/mixed blocks
             (if (and (= (aref (si-block-type si) gr ch) 2)
                      (= (aref (si-mixed si) gr ch) 0))
                 (setf (aref (si-region0-count si) gr ch) 8)
                 (setf (aref (si-region0-count si) gr ch) 7))
             (setf (aref (si-region1-count si) gr ch)
                   (- 20 (aref (si-region0-count si) gr ch))))
            (t
             (dotimes (r 3)
               (setf (aref (si-table-select si) gr ch r) (read-bits br 5)))
             (setf (aref (si-region0-count si) gr ch) (read-bits br 4)
                   (aref (si-region1-count si) gr ch) (read-bits br 3)
                   (aref (si-block-type si) gr ch) 0))))
        ;; preflag exists only in MPEG-1
        (when mpeg1p
          (setf (aref (si-preflag si) gr ch) (read-bit br)))
        (setf (aref (si-scalefac-scale si) gr ch) (read-bit br)
              (aref (si-count1table-select si) gr ch) (read-bit br))))
    si))
