;;;; src/ac3/tables.lisp — GENERATED by test/gen-ac3-tables.py.  Do not edit.
;;;;
;;;; Every constant AC-3 needs that is not derivable, transcribed mechanically from ffmpeg's
;;;; ac3tab.c, ac3.c and ac3dec_data.c by parsing the C rather than by retyping it.  The generator
;;;; asserts what each table has to be true of before emitting anything: band starts ascend and
;;;; span 0..253, every bin maps into its own band's range, the bit-allocation pointers are
;;;; monotonic in signal-to-mask ratio and lie in 0..15, and the log-add curve decays.  A table that
;;;; parsed wrong fails there rather than three layers down in the audio.
;;;;
;;;; The mantissa dequantisation tables are NOT here: they are a formula, (2m - (L-1))/L for an
;;;; L-level symmetric quantiser, and computing them says what they are.

(in-package #:reed)


(defparameter +ac3-frame-size+
  (make-array '(38 3) :element-type 'fixnum
    :initial-contents '((64 69 96) (64 70 96) (80 87 120) (80 88 120) (96 104 144) (96 105 144) (112 121 168) (112 122 168) (128 139 192) (128 140 192) (160 174 240) (160 175 240) (192 208 288) (192 209 288) (224 243 336) (224 244 336) (256 278 384) (256 279 384) (320 348 480) (320 349 480) (384 417 576) (384 418 576) (448 487 672) (448 488 672) (512 557 768) (512 558 768) (640 696 960) (640 697 960) (768 835 1152) (768 836 1152) (896 975 1344) (896 976 1344) (1024 1114 1536) (1024 1115 1536) (1152 1253 1728) (1152 1254 1728) (1280 1393 1920) (1280 1394 1920))))
(declaim (type (simple-array fixnum (38 3)) +ac3-frame-size+))

(defparameter +ac3-channels+
  (make-array 8 :element-type 'fixnum
    :initial-contents '(2 1 2 3 3 4 4 5)))
(declaim (type (simple-array fixnum (8)) +ac3-channels+))

(defparameter +ac3-sample-rate+
  (make-array 4 :element-type 'fixnum
    :initial-contents '(48000 44100 32000 0)))
(declaim (type (simple-array fixnum (4)) +ac3-sample-rate+))

(defparameter +ac3-bitrate+
  (make-array 19 :element-type 'fixnum
    :initial-contents '(32 40 48 56 64 80 96 112 128 160 192 224 256 320 384 448 512 576 640)))
(declaim (type (simple-array fixnum (19)) +ac3-bitrate+))

(defparameter +ac3-rematrix-band+
  (make-array 5 :element-type 'fixnum
    :initial-contents '(13 25 37 61 253)))
(declaim (type (simple-array fixnum (5)) +ac3-rematrix-band+))

(defparameter +ac3-bap+
  (make-array 64 :element-type 'fixnum
    :initial-contents '(0 1 1 1 1 1 2 2 3 3 3 4 4 5 5 6 6 6 6 7 7 7 7 8 8 8 8 9 9 9 9 10 10 10 10 11 11 11 11 12 12 12 12 13 13 13 13 14 14 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15)))
(declaim (type (simple-array fixnum (64)) +ac3-bap+))

(defparameter +ac3-slow-decay+
  (make-array 4 :element-type 'fixnum
    :initial-contents '(15 17 19 21)))
(declaim (type (simple-array fixnum (4)) +ac3-slow-decay+))

(defparameter +ac3-fast-decay+
  (make-array 4 :element-type 'fixnum
    :initial-contents '(63 83 103 123)))
(declaim (type (simple-array fixnum (4)) +ac3-fast-decay+))

(defparameter +ac3-slow-gain+
  (make-array 4 :element-type 'fixnum
    :initial-contents '(1344 1240 1144 1040)))
(declaim (type (simple-array fixnum (4)) +ac3-slow-gain+))

(defparameter +ac3-db-per-bit+
  (make-array 4 :element-type 'fixnum
    :initial-contents '(0 1792 2304 2816)))
(declaim (type (simple-array fixnum (4)) +ac3-db-per-bit+))

(defparameter +ac3-floor+
  (make-array 8 :element-type 'fixnum
    :initial-contents '(752 688 624 560 496 368 240 -2048)))
(declaim (type (simple-array fixnum (8)) +ac3-floor+))

(defparameter +ac3-fast-gain+
  (make-array 8 :element-type 'fixnum
    :initial-contents '(128 256 384 512 640 768 896 1024)))
(declaim (type (simple-array fixnum (8)) +ac3-fast-gain+))

(defparameter +ac3-band-start+
  (make-array 51 :element-type 'fixnum
    :initial-contents '(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 31 34 37 40 43 46 49 55 61 67 73 79 85 97 109 121 133 157 181 205 229 253)))
(declaim (type (simple-array fixnum (51)) +ac3-band-start+))

(defparameter +ac3-bin-to-band+
  (make-array 253 :element-type 'fixnum
    :initial-contents '(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 28 28 29 29 29 30 30 30 31 31 31 32 32 32 33 33 33 34 34 34 35 35 35 35 35 35 36 36 36 36 36 36 37 37 37 37 37 37 38 38 38 38 38 38 39 39 39 39 39 39 40 40 40 40 40 40 41 41 41 41 41 41 41 41 41 41 41 41 42 42 42 42 42 42 42 42 42 42 42 42 43 43 43 43 43 43 43 43 43 43 43 43 44 44 44 44 44 44 44 44 44 44 44 44 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49)))
(declaim (type (simple-array fixnum (253)) +ac3-bin-to-band+))

(defparameter +ac3-log-add+
  (make-array 260 :element-type 'fixnum
    :initial-contents '(64 63 62 61 60 59 58 57 56 55 54 53 52 52 51 50 49 48 47 47 46 45 44 44 43 42 41 41 40 39 38 38 37 36 36 35 35 34 33 33 32 32 31 30 30 29 29 28 28 27 27 26 26 25 25 24 24 23 23 22 22 21 21 21 20 20 19 19 19 18 18 18 17 17 17 16 16 16 15 15 15 14 14 14 13 13 13 13 12 12 12 12 11 11 11 11 10 10 10 10 10 9 9 9 9 9 8 8 8 8 8 8 7 7 7 7 7 7 6 6 6 6 6 6 6 6 5 5 5 5 5 5 5 5 4 4 4 4 4 4 4 4 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)))
(declaim (type (simple-array fixnum (260)) +ac3-log-add+))

(defparameter +ac3-quantization+
  (make-array 16 :element-type 'fixnum
    :initial-contents '(0 3 5 7 11 15 5 6 7 8 9 10 11 12 14 16)))
(declaim (type (simple-array fixnum (16)) +ac3-quantization+))

(defparameter +ac3-hearing-threshold+
  (make-array '(50 3) :element-type 'fixnum
    :initial-contents '((1232 1264 1408) (1232 1264 1408) (1088 1120 1200) (1024 1040 1104) (992 992 1056) (960 976 1008) (944 960 992) (944 944 976) (928 944 960) (928 928 944) (928 928 944) (928 928 944) (928 928 928) (912 928 928) (912 912 928) (912 912 928) (896 912 928) (896 896 928) (880 896 928) (880 896 928) (864 880 912) (864 880 912) (848 864 912) (848 864 912) (832 848 896) (832 848 896) (816 832 896) (800 832 880) (784 800 864) (768 784 848) (752 768 832) (752 752 816) (752 752 800) (752 752 784) (768 752 768) (784 768 752) (832 800 752) (912 848 752) (992 912 768) (1056 992 784) (1120 1056 816) (1168 1104 848) (1184 1184 960) (1120 1168 1040) (1088 1120 1136) (1088 1088 1184) (1312 1152 1120) (2048 1584 1088) (2112 2112 1104) (2112 2112 1248))))
(declaim (type (simple-array fixnum (50 3)) +ac3-hearing-threshold+))
